src/audit/template_injection.rs
=> feat: github.ref_name is always an injection risk

README.md
The boilerplate needed in a GitHub workflow to run `zizmor` and upload the SARIF file is very similar to the ESLint example in the GitHub docs, so linking directly to that will help make it clear how such a workflow can be written.
=> Link to GitHub workflow examples

Cargo.lock, Cargo.toml
Includes https://github.com/woodruffw/github-actions-models/pull/9, which fixes loading for some jobs that use `runs-on` with a group and no labels.
=> fix: bump github-actions-models

src/main.rs, src/registry.rs, src/sarif.rs
Fixes #57.
Example single SARIF location output with this change:
```json
{
"logicalLocations": [
{
"properties": {
"symbolic": {
"annotation": "does not set persist-credentials: false",
"name": "artipacked.yml",
"route": {
"components": [
{
"Key": "jobs"
},
{
"Key": "vulnerable-1"
},
{
"Key": "steps"
},
{
"Index": 0
}
]
}
}
}
}
],
"message": {
"text": "does not set persist-credentials: false"
},
"physicalLocation": {
"artifactLocation": {
"uri": ".github/workflows/artipacked.yml",
"uriBaseId": "%SRCROOT%"
},
"region": {
"endColumn": 80,
"endLine": 37,
"snippet": {
"text": "name: Checkout\n        uses: actions/checkout@v4\n\n      # NOT OK: upload-artifact archives entire repo, including persisted creds"
},
"sourceLanguage": "yaml",
"startColumn": 9,
"startLine": 34
}
}
}
```
(Observe …
=> fix: use relative workflow paths in SARIF output

src/main.rs
Fixes #76
I was also looking at whether color support should be modified when the terminal isn't a tty. I think this can be done by enabling supports-colors in owo_colors, although I'm not really a Rust dev and I couldn't quite figure out how to get this working right https://docs.rs/owo-colors/4.1.0/owo_colors/index.html#only-style-on-supported-terminals
=> fix: Always use the plain formatter even when the output is not a terminal

src/main.rs
`zizmor --version` now emits the version set in `Cargo.toml`
=> feat: show version

src/finding/mod.rs
👋 Hey William, thanks for this tool it is very useful !
Here is a tiny PR to fix the URLs displayed in the CLI reports, the current ones are returning a 404.
E.g: Artipacked is currently https://github.com/woodruffw/zizmor/tree/main/docs/audit/artipacked.md
but it should be https://github.com/woodruffw/zizmor/blob/main/docs/audits.md#artipacked
=> fix: finding url link to audits doc

src/audit/template_injection.rs
These are unique numbers assigned by GitHub and can't be used to inject shell commands.
Fixes #91
=> Exclude `github.run_*` from template injection check

.github/workflows/zizmor.yml
Setting permissions at the Job level, this overrides the parent `contents: read` setting, failing for private repositories.
=> fix(ci): move read permissions to job scope

.gitignore, Cargo.lock, Cargo.toml, tests/acceptance.rs, tests/test-data/artipacked.yml, tests/test-data/excessive-permissions.yml, tests/test-data/hardcoded-credentials.yml, tests/test-data/self-hosted.yml, tests/test-data/template-injection.yml, tests/test-data/use-trusted-publishing.yml
Closes #55 
I tried to cover all scenarios* that don't depend on the Github API token for now, but if you want I can add then by tweaking a bit the CI pipeline and using the `GITHUB_TOKEN` issued by GHA on these tests.
In addition, I did my best to make the tests read as simple as possible, moving some boilterplate into helper functions.
Let me know your thoughs!
=> test: adds acceptance tests on top of json-formatted output

.github/workflows/zizmor.yml, docs/usage.md, mkdocs.yml
Adds an annotated version of this repo's `zizmor.yml` to the docs.
See #89.
See #69.
=> docs: add an example GHA workflow

src/main.rs
Accept multiple individual files as inputs.
Useful with other mutli-file processing like xargs or other tools, so as to not have to invoke zizmor multiple times, and distinct from operating on an entire directory.
=> feat: accept multiple arguments as inputs

.pre-commit-hooks.yaml, docs/usage.md
=> feat: pre-commit hook for other repos to use

docs/usage.md
Not sure why, but pymdown or whatever is being used under the hood here doesn't like detached links where the identifier has backticks. They work like this, though.
CC @miketheman
=> chore: fix some usage links

src/render.rs
This helps the user rest comfortably at night, knowing that zizmor found an issue, but correctly ignored it per user request.
=> Include a count of ignored rules when no issues are found

docs/configuration.md, docs/usage.md, mkdocs.yml, src/audit/artipacked.rs, src/audit/impostor_commit.rs, src/audit/known_vulnerable_actions.rs, src/audit/ref_confusion.rs, src/audit/self_hosted_runner.rs, src/config.rs, src/main.rs, src/render.rs, src/state.rs
=> feat: configuration file support

Cargo.lock, Cargo.toml, src/expr/mod.rs
Reduce the amount of explicit boxing needed.
=> refactor: clean up expr APIs slightly

src/audit/template_injection.rs
GitHub provides the following and I don't see a way an attacker could hijack them:
* runner.debug
* runner.os
* runner.temp
(runner.arch was already excluded from the check)
=> feat: Exclude safe values from template injection rule

src/audit/template_injection.rs, src/expr/expr.pest, src/expr/mod.rs, src/finding/mod.rs
~~WIP, needs tests.~~
This will improve `template-injection`'s precision by allowing it to filter expressions that are "safe," i.e. can't produce arbitrary input-derived code regardless of how they're executed.
For now, as "safe" expression is defined as:
1. Any primitive (null, number, string, etc.)
2. `!{expr}`
3. `{expr} == {expr}` and `{expr} != {expr}`
4. Any other binary expression where both the LHS and RHS are themselves safe per cases 1-3
Notably, this means that some expressions that contain code or can be evaluated to code *will* be considered safe, since that code will effectively be static within those expressions and not derived from user input (i.e. context accesses).
=> feat: analyze expressions for safety

docs/usage.md, src/finding/mod.rs, src/main.rs, src/registry.rs, src/render.rs, src/sarif.rs, tests/acceptance.rs
This adds consistent error codes to `zizmor`. The meanings of the codes are added to the docs as well, but to copy them here:
| Code | Meaning |
| ---- | ------- |
| 0    | Successful audit; no findings to report. |
| 1    | Error during audit; consult output. |
| 10   | One or more findings found; highest finding is "unknown" level. |
| 11   | One or more findings found; highest finding is "informational" level. |
| 12   | One or more findings found; highest finding is "low" level. |
| 13   | One or more findings found; highest finding is "medium" level. |
| 14   | One or more findings found; highest finding is "high" level. |
Closes #86.
=> feat: exit code support

src/audit/template_injection.rs
=> fix: github.event.merge_group.base_sha is a safe context

src/audit/template_injection.rs
This would seem to fall into the category of "if these values are unsafe, we have bigger problems to deal with"
=> fix: exclude information about the repo and owner

docs/audits.md
Uses the MagicLink extension to provide nice looking links here:
Reference links don't support backticks: https://github.com/Python-Markdown/markdown/issues/495
=> fix(docs): fix repo links

docs/usage.md
Ciao! Didn't open an issue for this as it seemed straightforward. I know you suggest the users to update the hook version, but I figured it wouldn't be bad to update from time to time.
This pull request consists of an update to the documentation to reflect the latest version of zizmor in the suggested pre-commit-config file.
* [`docs/usage.md`](diffhunk://#diff-72376d0b487d7231cf31959bf266f6aea098e899743bae02e36d176cef4db476L186-R186): Updated the version of the `zizmor` repository from `v0.1.6` to `v0.3.0` in the `.pre-commit-config.yaml` file.
=> docs: update version in pre-commit hook

Cargo.lock, Cargo.toml, docs/snippets/help.txt, docs/usage.md, src/main.rs
Disables the special (>10) exit codes when
`--no-exit-codes` or `--format sarif` is passed,
leaving just success (0) and general tool failure
(1).
Closes #153.
=> feat: --no-exit-codes + sarif tweaks

src/audit/impostor_commit.rs, src/github_api.rs
We expect the majority of sha refs to be pointed to directly by a branch or a tag, so we can do a bit of fast path by checking those first.
This results in a 70% speedup for some contrived local cases.
=> perf: speed up impostor-commit's fast path

src/main.rs, src/registry.rs
This fixes a regression when error codes were added: we began suppressing the actual error message, making it much harder to diagnose errors in e.g. workflow parsing.
=> fix(cli): fixup error printing

src/render.rs
Fix "1 findings" -> "1 finding" and keep "2 findings".
```console
❯ zizmor .
🌈 completed main.yml
🌈 completed deploy.yml
🌈 completed lint.yml
warning[artipacked]: credential persistence through GitHub Actions artifacts
--> /Users/hugo/github/cherry-picker/.github/workflows/lint.yml:16:9
|
16 |       - uses: actions/checkout@v4
|         ------------------------- does not set persist-credentials: false
|
= note: audit confidence → Low
1 findings: 0 unknown, 0 informational, 0 low, 1 medium, 0 high
```
```console
❯ /tmp/zizmor/target/debug/zizmor .
🌈 completed lint.yml
🌈 completed main.yml
🌈 completed deploy.yml
warning[artipacked]: credential persistence through GitHub Actions artifacts
--> /Users/hugo/github/cherry-picker/.github/workflows/lint.yml:16:9
|
16 |       - uses: …
```
=> Fix singular and plural for 'findings'

src/audit/ref_confusion.rs, src/audit/template_injection.rs
One of these likely causes a bug in functionality.
Here's the correct spelling also in the docs:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
Found with https://github.com/codespell-project/actions-codespell.
=> Fix typos including `github.repostoryUrl` -> `github.repositoryUrl`

.github/workflows/site.yml
This currently fails for forks:
```
Run actions/configure-pages@v5
Error: Get Pages site failed. Please verify that the repository has Pages enabled and configured to build using GitHub Actions, or consider exploring the `enablement` parameter for this action. Error: Not Found - https://docs.github.com/rest/pages/pages#get-a-apiname-pages-site
Error: HttpError: Not Found - https://docs.github.com/rest/pages/pages#get-a-apiname-pages-site
```
https://github.com/hugovk/zizmor/actions/runs/11869198332/job/33079257598
Skip the Pages setup and deploy, keep the site build and artifacts upload, so forks can ensure they don't break the docs build.
=> Only deploy to GitHub Pages for upstream

docs/development.md, src/audit/known_vulnerable_actions.rs, src/audit/mod.rs, src/audit/template_injection.rs, src/audit/unpinned_uses.rs, src/audit/use_trusted_publishing.rs, src/models.rs
Very WIP. 
TODO:
The plan here is to refactor `WorkflowAudit` so that it contains a waterfall of default calls:
```
audit -> audit_{normal,reusable}_job -> audit_step
```
...which will enable simpler audit implementations, since an audit that only deals with individual steps will be able to implement just `audit_step` without having to write the outer loops + filtering manually.
CC @ubiratansoares -- this refactor might interest you, since it should make writing audits much more fluid/fluent :slightly_smiling_face:
=> refactor: simplify use of WorkflowAudit trait

docs/development.md, src/audit/artipacked.rs, src/audit/dangerous_triggers.rs, src/audit/excessive_permissions.rs, src/audit/hardcoded_container_credentials.rs, src/audit/impostor_commit.rs, src/audit/insecure_commands.rs, src/audit/known_vulnerable_actions.rs, src/audit/mod.rs, src/audit/ref_confusion.rs, src/audit/self_hosted_runner.rs, src/audit/template_injection.rs, src/audit/unpinned_uses.rs, src/audit/use_trusted_publishing.rs, src/finding/mod.rs, src/main.rs, src/render.rs
This adds the `Audit` supertrait, which can be quickly implemented for a type via the `audit_meta!(...)` macro.
This supertrait serves two purposes:
1. It allows us to do some deduplication/boilerplate reduction on individual audit trait impls;
2. It unlocks identity/context sharing between workflow audits and (to-be-implemented) action audits, since both can have `Audit` as a supertrait.
=> refactor: add Audit supertrait

src/finding/mod.rs, src/main.rs, src/models.rs, src/registry.rs, tests/acceptance.rs, tests/test-data/inlined-ignores.yml
Closes #124 
There are 2 approaches here
- https://github.com/woodruffw/zizmor/commit/8f1a18cd3ec00da493502df35abacd1ec32756f4 propose a change at `FindingRegistry` level
- https://github.com/woodruffw/zizmor/commit/14d2dd04b0341fa176b2ad6e2ebbc5073243e076 proposes a change at `FindingBuilder` level
In both of them the core remains the same : 
- we cache the YAML string contents at `Workflow` 
- we use `Finding.location` to extract the start and end rows related to the impacted snippet
- we loop through the lines, checking whether or not we have a comment disabling that particular check
Happy to iterate on this idea. If one of them makes sense, happy to add a commit with proper docs
How to test
- Pull this branch
- Run
```bash
cargo run -- tests/test-data/inlined-ignores.yml
```
```
➜ …
```
=> feat: adds support to inlined ignores

docs/snippets/help.txt, docs/usage.md, src/finding/mod.rs, src/main.rs, src/registry.rs
This adds `--min-severity`, which can be given
a severity level to filter any findings below
that level.
For example:
```
zizmor --min-severity=high
```
will filter any findings below "high," i.e."
findings at unknown, informational, low,
or medium.
Closes #60.
=> feat: add `--min-severity`

docs/audits.md, docs/configuration.md, docs/development.md, docs/installation.md, docs/usage.md, mkdocs.yml
These enrich the metadata and social cards
slightly. Not all pages have custom descriptions,
since the site-wide `site_description` is adequate in some cases.
See #79.
=> docs: add page descriptions

docs/snippets/help.txt, docs/usage.md, src/finding/mod.rs, src/main.rs, src/registry.rs
This adds `--min-confidence`, similar to
`--min-severity` (https://github.com/woodruffw/zizmor/pull/193), which can be given a
confidence level to filter any findings below that
specific confidence level.
For example:
```
zizmor --min-confidence=high
```
will filter any finding below "high", i.e.
findings at unknown, low, or medium confidence.
=> feat: add `--min-confidence`

docs/audits.md, src/audit/dangerous_triggers.rs, src/audit/github_env.rs, src/audit/mod.rs, src/main.rs, src/models.rs, tests/acceptance.rs, tests/test-data/github_env.yml
- Pulls dangerous triggers detection logic from `WorkflowAudit` and moves to `impl DangerousTriggers` instance methods
- Reuses only that logic in the context of to implement a new audit
```bash
cargo run -- tests/test-data/github_env.yml
error[github-env]: dangerous use of $GITHUB_ENV
--> tests/test-data/github_env.yml:12:9
|
12 |           run: |
|  _________^
13 | |           message=$(echo "$TITLE" | grep -oP '[{\[][^}\]]+[}\]]' | sed 's/{\|}\|\[\|\]//g')
14 | |           echo "message=$message" >> $GITHUB_ENV
| |_________________________________________________^ GITHUB_ENV used in the context of a dangerous Workflow trigger
|
= note: audit confidence → High
2 findings (1 ignored): 0 unknown, 0 informational, 0 low, 0 medium, 1 high
```
Some questions below!
=> feat: adds new github-env audit

Cargo.lock, Cargo.toml, src/audit/github_env.rs
Per #197 -- this improves our precision by only matching things that resemble writes to `$GITHUB_ENV`, e.g. `... >> $GITHUB_ENV`.
There are probably other patterns we should detect, and this is still very primitive. Longer term, we need to perform some degree of actual parsing here.
=> feat: improve precision for github-env

docs/audits.md, src/audit/unpinned_uses.rs, src/models.rs, tests/acceptance.rs, tests/test-data/artipacked.yml, tests/test-data/inlined-ignores.yml, tests/test-data/template-injection.yml, tests/test-data/use-trusted-publishing.yml
Here's my first pass at implementing #179. The code is there and functional, AFAICT. I've tested it against a real workflow file that uses repo paths. I don't have any handy that use Docker, but if I understand the model correctly, it's very straightforward to check it and so my code will Just Work™.
~~I will add tests and docs before I remove the "WIP" from this, but I wanted to make sure what I've done here is generally acceptable before I put effort into that part.~~
~~Since most of the "what to do if we find an unpinned `uses` of either flavor" is repetitive, I tossed in a flag instead of repeating that code.~~
There's a lot of "not" in the new function I created in the model. It could have been written a little more cleanly without the negations, but that kept the usage the same as …
=> Split unpinned-uses into two separate checks

Cargo.lock, Cargo.toml, src/audit/github_env.rs
A follow-up for #197 
Here we leverage [tree-sitter-bash](https://crates.io/crates/tree-sitter-bash) rather than regexes to match usages of `$GITHUB_ENV` within a Bash script body. 
I took a simple approach, getting the full expansion for a `file_redirect` or `pipeline` and matching inner contents. Perhaps I'm missing some corner cases, but at least we have a starting point to iterate over 🙂
I also added some additional test cases (comments) and prepared the implementation to match against other types of shells in upcoming PRs.
=> feat: even more precision for bash steps in github-env

src/audit/github_env.rs
This adds very primitive Windows Batch (i.e. `cmd.exe`) handling to the `github-env` audit, along with some testcases.
See https://github.com/woodruffw/zizmor/issues/197.
=> feat: primitive Windows batch handling in github-env

docs/audits.md, src/audit/unpinned_uses.rs
Makes the pinned-but-unhashed check `--pedantic`-only for now, since I'm still working out how to model sensitivities/auditing personas.
=> feat: unpinned-uses: make unhashed check pedantic for now

Cargo.lock, Cargo.toml, docs/development.md, tests/acceptance.rs, tests/common.rs, tests/snapshot.rs, tests/snapshots/snapshot__self_hosted-2.snap, tests/snapshots/snapshot__self_hosted.snap, tests/snapshots/snapshot__unpinned_uses-2.snap, tests/snapshots/snapshot__unpinned_uses.snap, tests/test-data/unpinned-uses.yml
This sets up the scaffolding for snapshot testing.
Right now the only snapshot testcases are for the `self-hosted` audit, but the idea here is that these snapshots will be useful for cross-audit testing + regression testing for real-world example workflows.
~~Needs docs.~~
Closes #218
=> test: snapshot tests

Cargo.lock, Cargo.toml, Makefile, docs/quickstart.md, docs/snippets/help.txt, docs/usage.md, src/audit/github_env.rs, src/audit/impostor_commit.rs, src/audit/known_vulnerable_actions.rs, src/audit/ref_confusion.rs, src/config.rs, src/finding/mod.rs, src/github_api.rs, src/main.rs, src/models.rs, src/registry.rs, src/render.rs, src/sarif.rs, src/state.rs, src/utils.rs, tests/snapshot.rs, tests/snapshots/snapshot__cant_retrieve.snap, tests/snapshots/snapshot__conflicting_online_options-2.snap, tests/snapshots/snapshot__conflicting_online_options-3.snap, tests/snapshots/snapshot__conflicting_online_options.snap
~~WIP.~~
Once finished, this will enable `zizmor foo/bar`, where `foo/bar` is a GitHub repo that `zizmor` will extract workflows to audit from.
~~(The `@`-prefix is not a firm design choice -- I might remove that.)~~
Closes #50
Closes #177
CC @miketheman as an interested party :slightly_smiling_face:
=> feat: remote auditing

mkdocs.yml
In f41f6925007350030316 a plugin list was added to the mkdocs config to add the "social" plugin. This removed the default "search" plugin (I assume by accident).
See https://www.mkdocs.org/user-guide/configuration/#plugins for the default plugins.
The plugin is quite handy for searching audit rules, etc., so fix it by adding "search" back to the enabled plugins.
=> docs: restore search plugin

.github/workflows/pypi.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, pyproject.toml
This will allow us to publish a bunch of wheels to PyPI, simplifying installation for a lot of users.
=> ci: add a maturin matrix for PyPI releases

Cargo.lock, Cargo.toml, src/audit/insecure_commands.rs, tests/snapshot.rs, tests/snapshots/snapshot__insecure_commands-2.snap, tests/snapshots/snapshot__insecure_commands.snap, tests/test-data/insecure-commands.yml
See https://github.com/woodruffw/github-actions-models/pull/21.
There are certainly other places where the `env:` can be non-static, but this gets us started.
The only place where this currently affects zizmor is in the `insecure-commands` audit -- I've refactored it so that a non-static `env:` produces an "auditor" persona finding.
CC @ubiratansoares for viz, since you wrote this audit :slightly_smiling_face:
=> fix: handle non-static env: in job steps

Cargo.lock, Cargo.toml, src/audit/artipacked.rs, src/audit/dangerous_triggers.rs, src/audit/excessive_permissions.rs, src/audit/github_env.rs, src/audit/hardcoded_container_credentials.rs, src/audit/impostor_commit.rs, src/audit/insecure_commands.rs, src/audit/known_vulnerable_actions.rs, src/audit/mod.rs, src/audit/ref_confusion.rs, src/audit/self_hosted_runner.rs, src/audit/template_injection.rs, src/config.rs, src/finding/locate.rs, src/github_api.rs, src/main.rs, src/models.rs, src/registry.rs
~~Very WIP.~~
The basic idea here:
1. Remove `log` and `env_logger` entirely in favor of `tracing` and its crates
2. Work on making the `tracing_indicatif` spans as pretty as possible/as useful as possible
3. Evaluate if this is actually worth it?
Closes #40
=> refactor: experiment with tracing

docs/snippets/help.txt, src/main.rs
This is now obsolete, thanks to the tracing/
progress tracking unification. Most users who
were using this probably want `-q` instead.
BREAKING CHANGE: removes the `--no-progress` flag
=> feat: remove --no-progress

src/audit/template_injection.rs
See https://github.com/python/cpython/pull/127749#discussion_r1875069336 -- this took a bit of sleuthing, but the `pull_request` event body's `commits` field can only ever contain a number, meaning that it isn't itself a source of code injection.
Ref: https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request
=> fix: template-injection: ignore another safe context

docs/usage.md
This reduces the typical CI job time from ~2 minutes to seconds (or virtually instantaneous, in offline mode).
=> docs: switch GHA example to uvx

Makefile
Use `uvx --with-requirements` directly, since it's just as fast (if not faster).
See #256.
=> chore: Makefile: avoid a venv

docs/audits.md
See convo in https://github.com/python/cpython/pull/127749#discussion_r1875081281.
CC @sethmlarson @alexwaygood @hugovk
=> docs: add template-injection tips

src/github_api.rs
Fixes a small bug where we'd only download `foo.yml` and not `foo.yaml` when remote-auditing.
=> fix: download both .yml and .yaml from repos

Cargo.lock, Cargo.toml, tests/snapshots/snapshot__insecure_commands-2.snap, tests/snapshots/snapshot__insecure_commands.snap
This bumps to the latest patch version, which
is noted to fix a panic in string slicing.
Fixes https://github.com/woodruffw/zizmor/issues/263
See: https://github.com/rust-lang/annotate-snippets-rs/issues/161
=> fix: bump annotate-snippets to fix crash

src/audit/artipacked.rs, tests/snapshot.rs, tests/snapshots/snapshot__artipacked-3.snap, tests/snapshots/snapshot__artipacked.snap
Categorizing this as "pedantic" was incorrect,
since we're raising a finding for something the
user explicitly opted into, and that's what the
auditor persona is for.
=> fix: move artipacked pendantic finding to auditor

src/audit/self_hosted_runner.rs, src/models.rs
A follow-up from https://github.com/woodruffw/zizmor/pull/231
Just realised that we can expand the Matrix when instantiating, hence storing the expanded values as a field and avoiding a new expansion every time we need to evaluate the same matrix . 😄
=> feat: evaluates a matrix expansion only once

Makefile, docs/development.md, docs/snippets/render-trophies.py, docs/snippets/trophies.md, docs/snippets/trophies.txt, docs/trophy-case.md
This is a little overkill, but whatever.
Key changes:
* `trophies.txt` tracks the trophies now, one per line
* `make trophies` will generate `trophies.md` on demand from `trophies.txt`
* `trophies.md` gets embedded (via snippet) into `trophy-case.md`
This could have been done with `mkdocs-gen-files`, but keeping it separate from now will keep the site build as fast as possible and will (hopefully) make it less tempting to make the site even more dynamic.
=> docs: make the trophy case prettier

src/audit/use_trusted_publishing.rs, src/models.rs
Simplifies the audit itself slightly, and adds a `RepositoryUses::matches` helper that will be useful more generally.
=> refactor: simplify use-trusted-publishing slightly

src/audit/template_injection.rs
Adds another always-safe context to the safe list.
=> fix: template-injection: consider runner.tool_cache safe

docs/snippets/render-trophies.py, docs/snippets/trophies.md, docs/snippets/trophies.txt
=> docs: support commits in trophy case

docs/development.md
adds a missing `is` I've stumbled across while reading the docs.
=> docs: Fix typo in development.md

Cargo.lock, Cargo.toml, docs/snippets/help.txt, docs/usage.md, src/audit/github_env.rs, src/audit/impostor_commit.rs, src/audit/ref_confusion.rs, src/github_api.rs, src/main.rs, src/state.rs
I'm not 100% sure if this makes sense yet. Need to do some performance measurements.
TODOs:
Fixes https://github.com/woodruffw/zizmor/issues/52.
=> refactor: use http-cache for caching, optimize network calls

src/audit/template_injection.rs
`github.event.before` and `github.event.after` are always SHA references, when present.
`github.event.before` is documented but `github.event.after` is seemingly not -- I found independent corroboration here: <https://www.kenmuse.com/blog/the-many-shas-of-a-github-pull-request/>
See https://github.com/curl/curl/pull/15746.
=> fix: template-injection: more safe contexts

.github/workflows/ci.yml, .github/workflows/pypi.yml, .github/workflows/site.yml, .github/workflows/zizmor.yml
Uses `frizbee` to pin more workflows, plus adds a `rust-cache` step to the CI workflow to (hopefully) speed it up a bit.
=> ci: pin more workflows, enable rust-cache in tests

.github/workflows/pypi.yml
Having this matrix run on every PR badly messes with GHA's base ratelimits, since it does an incredible amount of cache reads/writes.
=> ci: disable wheel builds on pull_request

src/models.rs, tests/snapshot.rs, tests/snapshots/snapshot__template_injection-4.snap, tests/test-data/template-injection/pr-317-repro.yml
This tweaks #298 slightly, following the regression noted in https://github.com/woodruffw/zizmor/issues/22#issuecomment-2543128489 -- the previous `expands_to_static_values` only checked whether the expanded matrix value was *precisely* an expression, but we also need to handle the case where an expanded matrix value *contains* an expression.
By way of example:
```yaml
matrix:
include:
- foo: 123
bar: ${{ expression }} # correctly fails expands_to_static_values
- foo: 456
bar: prefix-${{ expression }} # incorrectly passes expands_to_static_values
```
I'll work on a testcase for this as well. CC @ubiratansoares for viz 🙂
=> fix: expands_to_static_values considers expressions inside strings

src/audit/artipacked.rs, src/audit/dangerous_triggers.rs, src/audit/excessive_permissions.rs, src/audit/github_env.rs, src/audit/hardcoded_container_credentials.rs, src/audit/impostor_commit.rs, src/audit/insecure_commands.rs, src/audit/known_vulnerable_actions.rs, src/audit/ref_confusion.rs, src/audit/self_hosted_runner.rs, src/audit/template_injection.rs, src/audit/unpinned_uses.rs, src/audit/use_trusted_publishing.rs, src/finding/mod.rs, src/models.rs, src/sarif.rs
This was pointed out by @fcasal: the current model assumes that all locations are equal, while SARIF distinguishes between "primary" locations (i.e. those in `locations`) and "secondary" locations (i.e. those in `relatedLocations`). This is especially relevant for SARIF presentation tools like GH itself, which assume that `locations` only contains a single member.
This tweaks our models and updates all audits to emit a "primary" location for the most salient part of each finding. The salient part of each finding is subjective.
This should improve the presentation quality for our SARIF outputs. One downside to this approach is that every audit needs to explicitly annotate a primary location.
Fixes #66.
=> feat: add 'primary' locations

src/sarif.rs
This PR
- fixes the schema used in the sarif files
- adds a rules section with the documentation URL 
- replaces the finding identifier with the finding description in the result's message 
When viewed with the Sarif Explorer VSCode extension,
Before
After
=> feat: Fix Sarif schema and add rules to Sarif files 

src/audit/excessive_permissions.rs, tests/snapshot.rs, tests/snapshots/snapshot__excessive_permissions-2.snap, tests/snapshots/snapshot__excessive_permissions.snap, tests/test-data/excessive-permissions/issue-336-repro.yml
This should reduce the amount of noise in single-job workflows, per #336.
CC @pietroalbini
Fixes #336.
=> fix: excessive-permissions: be less noisy on one-job workflows

src/audit/cache_poisoning.rs, tests/snapshot.rs, tests/snapshots/snapshot__cache_poisoning-10.snap, tests/test-data/cache-poisoning/publisher-step.yml
A first follow-up from #294. also contributing to #334 
We now have a list of well-know publisher Actions (2 of them so far 😄) and the audit inspects all the steps at once alongside with the previous trigger evaluation to determine whether the Workflow/Job actually builds artifacts for publishing.
I also introduced an `PublishingArtifactsScenario` enum to easilty match the situation we are dealing with and signal properly the non-primary locations in `FindingBuilders`.
=> feat: detects well-known publisher actions in cache-audit

src/audit/cache_poisoning.rs
Another contribution to #334 
I investigated the Github Marketplace along with public Github orgs out there to improve a a bit the list of publisher-like Actions. Added Actions from Docker, GCP, AWS, Azure and a few popular ones used to publish binaries to Github releases.
Should we document this in the official docs, maybe?
=> feat: adds more publish-aware actions to cache-audit

docs/usage.md
[Caught by dependabot](https://github.com/colindean/transmission-blocklist/pull/9) moments after I set it up in one of my repos.
=> Updates astral-sh/setup-uv action to v5

src/audit/template_injection.rs, src/expr/expr.pest, src/expr/mod.rs, tests/snapshot.rs, tests/snapshots/snapshot__template_injection-6.snap, tests/test-data/template-injection/issue-339-repro.yml
~~WIP;~~ These grammar changes mean the syntax tree itself is different, so I need to update the walk as well.
Fixes #339.
=> fix: handle context accesses following calls

src/audit/cache_poisoning.rs, tests/snapshot.rs, tests/snapshots/snapshot__cache_poisoning-11.snap, tests/test-data/cache-poisoning/issue-343-repro.yml
`setup-go`'s caching is on by default and opt-out with `cache=false`, https://github.com/actions/setup-go?tab=readme-ov-file#v4
Fixes [this](https://github.com/jmelahman/connections/blob/master/.github/workflows/release.yml) false positive,
=> fix: setup-go's cache-control is OptOut

src/audit/cache_poisoning.rs, tests/snapshot.rs, tests/snapshots/snapshot__cache_poisoning-12.snap, tests/test-data/cache-poisoning/caching-not-configurable.yml
Another follow-up for #334 
Here we tweak a bit the models for `CacheAwareAction`, moving into to an enum an introducing `Configurable` and `NotConfigurable` variants. 
The not-configurable variant covers Actions like [Mozilla-Actions/sccache-action](https://github.com/Mozilla-Actions/sccache-action), which always cache/restore and does not provide control inputs / control values to disable caching.
I added a snapshot test convering this new use case. Added some docs on the semantics of `CacheControlInput:OptIn` and `CacheControlInput:OptOut` as well.
=> feat: adds support to non-configurable caching on cache-audit

src/audit/cache_poisoning.rs
Another follow-up for #334.
Extends the list of known cache-aware Actions with the following
- https://github.com/mlugg/setup-zig
- https://github.com/oven-sh/setup-bun
- https://github.com/graalvm/setup-graalvm
- https://github.com/gradle/actions/blob/main/setup-gradle
- https://github.com/DeterminateSystems/magic-nix-cache-action
- https://github.com/docker/setup-buildx-action
- https://github.com/actions-rust-lang/setup-rust-toolchain
- https://github.com/nix-community/cache-nix-action
I did a search in both Github Marketplace and dependends of [actions/toolkit/cache](https://github.com/actions/toolkit/network/dependents?package_id=UGFja2FnZS0xMTc3OTQzMDA0) and filtered some of the most popular ones.
=> feat: augments the list of cache-aware action in cache-audit

src/audit/cache_poisoning.rs
~~WIP.~~ Trying to flatten the states here a bit.
=> refactor: cache control types

src/audit/cache_poisoning.rs, tests/snapshot.rs, tests/snapshots/snapshot__cache_poisoning-13.snap, tests/test-data/cache-poisoning/workflow-release-branch-trigger.yml
One more follow-up for #334
We now detect at least one common pattern for Workflows triggered with `push/branches`. Deploying when pushing to a convention release branch is quite common, and this change sets the stage to detect other similar branch filters in the future.
There is at least one additional PR to before finishing #334, raising it asap!
=> feat: detects push to release branches in cache-poisoning

src/models.rs
Closes #334 
Improves the implementation of `RepositoryUses::matches` so it becomes case-insensitive regarding a provided template.
I opted for case-insensitive comparisons rather than normalizing to a lowercased template because I see this approach introducing less changes, and all of them live within a single function.
=> feat: adds case-insensitive template matching for uses actions

Cargo.lock, Cargo.toml, src/audit/github_env.rs
~~Very WIP.~~
This experimentally replaces the stack-of-nodes approach with hand-written TS queries, which can be more precise about matches and their sub-captures (e.g. allowing us to match only when the RHS is actually a variable expansion).
It also adds some examples of false positives that the previous approach flagged. These FPs aren't likely to occur in the wild, however, so the direct benefit for actual users is pretty small.
The larger impact here is indirect:
* By switching to TS queries, we get full access to match and capture-level spanning information. We had this indirectly with the stack-of-nodes approach, but the query language makes it even simpler by giving us capture names 🙂 
* This unblocks a bugfix for #234 which would be challenging to generalize with the previous …
=> feat: github-env: use tree-sitter queries

src/audit/github_env.rs, tests/snapshot.rs, tests/snapshots/snapshot__github_env.snap, tests/test-data/github-env/action.yml
=> feat: github-env: support composite actions

docs/audits.md, src/audit/unpinned_uses.rs, tests/snapshot.rs, tests/snapshots/snapshot__unpinned_uses-3.snap, tests/test-data/unpinned-uses/action.yml
Contributes to #350 
I tried to dedup a bit the inner logic for this audit by extracting at least one common function. I do think there is room for more deduplication, but I did not want to push hard on that in the first take. 
Let me know your thoughts 🙂
=> feat: adds unpinned-uses support to composite actions

docs/audits.md, src/audit/ref_confusion.rs
Contributes to #350 
This one should be trivial, since most of machinery was in place (including the handy `RefConfusion::confusable` method) 😄
I miss here the good vibes after running snapshot tests locally, but #306 will bring the chance to catch up for this audit 🙂
=> feat: ref-confusion now supports composite actions

docs/audits.md, src/audit/known_vulnerable_actions.rs
Another follow-up for #350. Very similar to #365.  🙂
=> feat: adds composite actions support to known-vulnerable-actions

docs/index.md
A follow-up for #377 . 
Just checked `zizmor` website and there is one beta warning  left at `docs/index.md`. Removed just in case 😄
=> docs: ditches beta warning from static website

src/audit/cache_poisoning.rs, src/models.rs, src/models/coordinate.rs
WIP.
This is the first part of #378: it generalizes `CacheAwareAction` into `UsesCoordinate`, which we can then reuse for conditions on the publish step as well.
=> refactor: CacheAwareAction -> UsesCoordinate

.github/workflows/pypi.yml
This ensures that we only restore from the cache
on normal branch and workflow_dispatch activity,
while runs from tags are always done fully
from scratch.
=> ci: disable sccache if the ref is a tag

src/audit/cache_poisoning.rs, src/models.rs, src/models/coordinate.rs
See #378; follows #383.
This generalizes the "coordinate usage" semantics from caching actions to anything that might be configurable.
Needs additional tests.
=> refactor: generalize coordinate usage semantics

docs/release-notes.md, src/audit/cache_poisoning.rs, tests/snapshot.rs, tests/snapshots/snapshot__cache_poisoning-14.snap, tests/test-data/cache-poisoning/issue-378-repro.yml
This fixes #378: we now use the generalized `UsesCoordinate` to handle `docker/build-push-action` with `push: false`, meaning that we no longer emit a false positive finding in that case.
This also adds a repro testcase, ensuring that we don't regress.
=> fix: cache-poisoning: handle non-pushing docker-push-action

docs/audits.md, docs/release-notes.md, src/audit/github_env.rs, tests/snapshot.rs, tests/snapshots/snapshot__github_env-2.snap, tests/snapshots/snapshot__github_env.snap, tests/test-data/github-env/github-path.yml
This generalizes the `github-env` audit so that it detects `GITHUB_PATH` writes as well, and renders them appropriately. It also generalizes the finding production within the audit, so that multiple findings can be produced per step instead of terminating at the first finding.
Closes #384.
=> feat: github-env audit checks GITHUB_PATH too

docs/audits.md
I had to reformat the remainder of the paragraph to not exceed EOL 80.
=> Documentation: add missing word "to"

docs/release-notes.md, src/audit/github_env.rs, src/audit/template_injection.rs, src/models/coordinate.rs
Fixes a small FP where `github.action_path` would be flagged despite being 100% runner controlled.
=> fix: template-injection: github.action_path is safe

docs/release-notes.md, src/audit/github_env.rs, src/models.rs, src/utils.rs, tests/snapshot.rs, tests/snapshots/snapshot__github_env-3.snap, tests/test-data/github-env/issue-397-repro.yml
This normalizes the shell before we match it, allowing us to handle cases like in #397.
Fixes #397.
=> fix: handle non-trivial shells in github-env

docs/audits.md, docs/release-notes.md, src/audit/mod.rs, src/audit/secrets_inherit.rs, src/main.rs, src/models.rs, tests/snapshot.rs, tests/snapshots/snapshot__secrets_inherit.snap, tests/test-data/secrets-inherit.yml
Adds a `secrets-inherit` audit, which detects and flags usage of `secrets: inherit` in reusable workflow calls.
=> feat: secrets-inherit: new audit

docs/release-notes.md, src/audit/template_injection.rs
Fixes another FP from an always-safe context.
h/t @sharkdp @AlexWaygood
See: https://github.com/astral-sh/ruff/pull/15361
=> fix: template-injection: github.server_url is safe

README.md
currently the demo link on pypi is not working, updating to use a static link
=> fix: update to use static link for PyPI display

Cargo.lock, Cargo.toml, src/audit/artipacked.rs, src/audit/cache_poisoning.rs, src/audit/impostor_commit.rs, src/audit/known_vulnerable_actions.rs, src/audit/ref_confusion.rs, src/audit/template_injection.rs, src/audit/unpinned_uses.rs, src/audit/use_trusted_publishing.rs, src/github_api.rs, src/main.rs, src/models.rs, src/models/coordinate.rs, src/models/uses.rs, src/registry.rs, tests/snapshot.rs, tests/snapshots/snapshot__template_injection-8.snap, tests/test-data/template-injection/pr-425-backstop/action.yml
~~WIP.~~
This will allow me to remove the `uses()` and `with()` trait methods, which encode unnecessary runtime error states.
More fully, this implies that the `Uses` model needs to be pushed into `github_actions_models` and made into a hard parsing invariant (i.e. we should fail to parse if a `uses:` clause is invalid).
xref https://github.com/woodruffw/github-actions-models/pull/29
=> refactor: add StepBodyCommon

docs/release-notes.md, src/audit/template_injection.rs
`github.event.pull_request.base.sha` is always a SHA reference.
=> bugfix: mark another context as safe during injections

docs/release-notes.md, src/main.rs, src/registry.rs, src/sarif.rs
This changes the SARIF generation so that `physicalLocations` now always contains an absolute path to the input. This is a slight over-correction of the previous behavior, which would use a repo-relative path when possible and fall back on the filename component when it couldn't infer one.
In practice, the trick used by the previous behavior worked well for workflow path (which are always under `.github/workflows` but doesn't generalize for action paths, which can be anywhere. As a result there's no "anchor" to distinguish the repository prefix from the rest of the path.
This should have no negative effect on most users: local users will have their full paths in the SARIF instead, as will remote (GitHub Actions) users. In the latter case, GitHub Advanced Security should be able to …
=> bugfix: sarif: use absolute physical locations only

docs/audits.md, docs/release-notes.md, src/audit/bot_conditions.rs, src/audit/mod.rs, src/main.rs, src/models.rs, tests/snapshot.rs, tests/snapshots/snapshot__bot_conditions.snap, tests/test-data/bot-conditions.yml
Implements the `bot-conditions` audit.
This audit isn't as precise as it could be (a few FPs are noted in the comments), but it's a decent start.
This also revealed some expr parser deficiencies, which I'll handle in a follow-up.
Closes #170.
=> feat: bot-conditions

docs/release-notes.md, src/expr/expr.pest, src/expr/mod.rs
This was revealed with #460 -- multi-line expressions are supported by GHA, but we weren't allowing newlines as a whitespace token.
=> bugfix: parse multi-line expressions correctly

Makefile, pyproject.toml, site-requirements.txt
Everything is now in pyproject.toml, so we don't need the site-requirements.txt file anymore.
=> chore: remove site-requirements.txt

docs/release-notes.md, src/audit/bot_conditions.rs, src/main.rs, src/models.rs, src/registry.rs, src/render.rs, src/sarif.rs
Fixes #468.
See https://github.com/woodruffw/zizmor/issues/452 for earlier context.
=> bugfix: generalize path prefix handling

.github/workflows/zizmor.yml, Cargo.lock, Cargo.toml, docs/release-notes.md, src/audit/excessive_permissions.rs, src/models.rs, src/registry.rs, tests/snapshot.rs, tests/snapshots/snapshot__excessive_permissions-10.snap, tests/snapshots/snapshot__excessive_permissions-11.snap, tests/snapshots/snapshot__excessive_permissions-12.snap, tests/test-data/excessive-permissions/issue-472-repro.yml, tests/test-data/excessive-permissions/reusable-workflow-call.yml, tests/test-data/excessive-permissions/reusable-workflow-other-triggers.yml
This tweaks the `excessive-permissions` audit in the following ways:
1. When a workflow is purely a reusable workflow (i.e. has `workflow_call` and no other triggers), we emit pedantic findings instead of regular ones. In effect, we assume that the caller workflow sets the right permissions when calling the reusable workflow.
2. We now check `permissions:` for reusable job calls, and emit a regular finding if a reusable call does not explicitly set permissions. This effectively covers (1) by checking the caller workflow.
If I'm thinking about this correctly, this combination should strike a reasonable balance between signal and noise: reusable workflow callers *should* always be setting permissions explicitly, and reusable workflows themselves shouldn't be flagged unless other conditions …
=> bugfix: special-case workflow_call in excessive-permissions

docs/release-notes.md, src/github_api.rs, src/main.rs
Fixes #474.
Old:
```
invalid gzip header
```
New:
```
error: couldn't collect inputs from https://github.com/fake/fake
= note: confirm the repository exists and that you have access to it
Caused by:
failed to fetch https://api.github.com/repos/fake/fake/tarball/HEAD: 404 Not Found
```
=> feat: improve error message when repo fetch fails

docs/release-notes.md, src/main.rs
This ensures that we discover actions defined within subdirectories of `.github/workflows` correctly, e.g. `.github/workflows/foo/action.yml`
Fixes #394.
=> bugfix: collect actions from subdirectories of .github/workflows

src/audit/mod.rs
When clicking the links in warnings, like:
```
warning[excessive-permissions]: overly broad permissions
```
Takes you to a page like:
`https://woodruffw.github.io/zizmor/audits#excessive-permissions`
Which quickly redirects to:
`https://woodruffw.github.io/zizmor/audits/#excessive-permissions`
But we might as well link directly there, to avoid a little jump in the URL.
=> Add slash to avoid redirect

docs/release-notes.md, src/registry.rs, tests/snapshot.rs, tests/snapshots/snapshot__invalid_inputs.snap, tests/test-data/invalid/invalid-workflow.yml
This slightly improves the parse error when loading an arbitrary file, by showing the entire error stack for both the failed workflow parse and the failed composite action parse.
=> feat: improve parse error slightly

Cargo.lock, Cargo.toml, docs/release-notes.md
This fixes a bug where we'd fail to parse Action
definitions that are missing a `name`.
=> deps: bump github-actions-models

docs/release-notes.md, src/audit/bot_conditions.rs, src/audit/overprovisioned_secrets.rs, src/audit/template_injection.rs, src/expr/mod.rs
This refactors context handling to be more generic/consistent. In particular, it aims to ensure that we do case-insensitive context comparisons as often as possible, since that's what GitHub itself does (i.e. `github.ref == GITHUB.REF`).
It also removes a few more persistent sources of unneeded allocations/reallocations of strings, although there's still a lot that could be done there.
=> refactor: improve context handling

Cargo.lock, Cargo.toml
Zizmor v1.2.2 installed via Cargo does not compile on ubuntu (works fine on MacOS though).
Example:
-  https://github.com/pypi/warehouse/actions/runs/13011768769/job/36290925535
- https://github.com/huggingface/peft/actions/runs/13009492925/job/36283783626
The problem stems from `tracing-indicatif`:
```bash
root@8c9cc7047c95:/zizmor# CARGO_TARGET_DIR=/tmp/cargo-install5wZQo3/ cargo install zizmor --version 1.2.2 --jobs=1
Updating crates.io index
Installing zizmor v1.2.2
Updating crates.io index
Locking 314 packages to latest compatible versions
Adding github-actions-models v0.22.0 (available: v0.23.0)
warning: profile package spec `insta` in profile `dev` did not match any packages
Did you mean `idna`?
warning: profile package spec `similar` in profile `dev` did not match any packages …
```
=> Downgrade tracing-indicatif

Cargo.lock, Cargo.toml, docs/release-notes.md
Fixes an edge case in modeling `max-parallel`; see https://github.com/woodruffw/github-actions-models/issues/35.
=> bugfix: bump github-actions-models to 0.25.0

docs/release-notes.md, docs/usage.md, src/finding/mod.rs
We now allow trailing comments after the ignore rule list, which is useful for self-documenting ignores.
Closes #513.
=> feat: relax ignore comment regex

Cargo.lock, Cargo.toml, docs/release-notes.md
This bumps to the latest `github-actions-models`, which fixes a parse failure on workflows that have `workflow_dispatch` triggers with non-string inputs.
Fixes #562.
=> bugfix: bump github-actions-models to 0.26.0

docs/release-notes.md, src/audit/unredacted_secrets.rs, tests/snapshots/snapshot__unredacted_secrets.snap
Didn't catch this with the 1.4.0 release.
=> bugfix: fix audit id for unredacted secrets audit

docs/release-notes.md, src/main.rs, src/models.rs, src/registry.rs, src/render.rs, src/sarif.rs
Tried this on some local directories (multiple at a time) and got reasonable outputs that were unambiguous.
Fixes #571.
h/t @alex
=> bugfix: don't remove prefixes from local paths

docs/release-notes.md, src/audit/overprovisioned_secrets.rs, src/expr/mod.rs
This detects patterns like `secrets[...]` where `...` is not a string literal, since these are similar to `toJSON(secrets)` in that they cause the entire context to be injected into the runner.
Closes #551.
=> feat: detect overprovisioned `secrets[...]`

.github/workflows/pypi.yml
See: https://github.com/PyO3/maturin-action/releases/tag/v1.47.2
See: https://github.com/PyO3/maturin-action/pull/330
=> ci: pypi: bump maturin-action to v1.47.2

docs/release-notes.md, docs/snippets/help.txt, src/main.rs
This was removed in 0.9.0 with the `tracing_indicatif` refactor, but I'm realizing that it's useful to have regardless.
In particular, this will help users in contexts where their integration *is* (or pretends to be) a terminal, but that terminal doesn't support interactive behaviors like progress bars. In particular, users of `pre-commit.ci` will be able to use this to prevent the progress bar from spamming their outputs.
See https://github.com/woodruffw/zizmor/issues/582.
=> cli: re-add `--no-progress` flag

docs/release-notes.md, src/main.rs
=> bugfix: don't require `.git/` to respect `.gitignore` files

.github/workflows/pypi.yml
The wheels of justice turn slowly, but grind exceedingly fine.
See: https://github.com/actions/runner-images/issues/11637#issuecomment-2720420481
=> ci: pypi: bump to macos-14

.github/workflows/pypi.yml, docs/installation.md, docs/release-notes.md
Using auto causes us to default to exceptionally
old versions of glibc, along with containers that
struggle badly to build things like tree-sitter.
See: https://github.com/tree-sitter/tree-sitter/issues/4186
See: https://github.com/tree-sitter/tree-sitter/issues/4271
=> ci: pypi: use manylinux_2_28 consistently

Cargo.lock, Cargo.toml, src/audit/github_env.rs
Handled implicitly via tree-sitter now.
=> chore: drop explicit dependency on streaming-iterator

docs/usage.md
This clarifies the documentation on where ignore comments should be placed. In particular, it makes the implicit requirement that the comment be parsed as part of the YAML AST more explicit, and gives an example of an incorrect, ineffective ignore comment.
See #612.
=> docs: usage: clarify ignore comment placement

docs/usage.md
=> Clearly state that `actions: read` is only required for private repos

docs/development.md, docs/release-notes.md, src/audit/template_injection.rs, src/finding/mod.rs, src/models.rs, src/render.rs, src/sarif.rs, tests/integration/e2e.rs, tests/integration/snapshots/integration__e2e__issue_612_repro.snap, tests/integration/test-data/issue-612-repro/action.yml
~~WIP.~~
Things I need to do here:
* Add the concept of an "invisible" span, which is used for evaluating ignore comments but not presented in outputs like SARIF or the terminal render.
* Add invisible spans to audits where appropriate.
Fixes #612.
=> tests: add repro case for #612

.github/workflows/test-sarif.yml, docs/release-notes.md, src/main.rs, src/registry.rs, src/sarif.rs
Fixes #604.
This performs the fix by partially reverting #572 -- the "presentation" path is still used in formats like the "plain" (cargo-style) output, but the SARIF format now uses a `sarif_path` helper that removes the input prefix (even when that input prefix is something relative that GitHub _should_ be handling correctly).
To test this, I've added a new `test-sarif` workflow that gets triggered by the `test-sarif-presentation` label -- when a PR is labeled as such, the workflow runs and uses a custom category to test any SARIF changes made. 
~~I don't have a good way to test this yet -- my initial thought was to add some kind of `issue_comment` trigger so that I could do something like `/sariftest`, but I don't really like that. Another option would be a `pull_request` with the …
=> bugfix: sarif: add working directory to invocation

docs/release-notes.md, src/sarif.rs
GitHub treats rules as "non-security" by default. All `zizmor` rules are security rules, so this just marks them as such so that GitHub tags each finding/result correctly.
~~WIP.~~
=> feat: attempt to mark SARIF results as security findings

docs/release-notes.md, src/audit/overprovisioned_secrets.rs, src/audit/template_injection.rs, src/audit/unredacted_secrets.rs, src/expr/mod.rs, tests/integration/snapshots/integration__snapshot__template_injection-6.snap, tests/integration/test-data/template-injection/dataflow.yml
Fixes #624.
This will make audits like `template-injection` more precise.
=> feat: basic dataflow for context expansion

docs/release-notes.md, src/audit/cache_poisoning.rs
Adds [`jdx/mise-action`](https://github.com/jdx/mise-action), the action to setup [`mise-en-place`](https://mise.jdx.dev/), to `KNOWN_CACHE_AWARE_ACTIONS`.
Related: #629
=> feat: cache-poisoning: add jdx/mise-action to cache aware actions

docs/release-notes.md, src/audit/cache_poisoning.rs, src/models.rs, src/models/coordinate.rs, tests/integration/snapshot.rs, tests/integration/snapshots/integration__snapshot__cache_poisoning-15.snap, tests/integration/test-data/cache-poisoning/issue-378-repro.yml, tests/integration/test-data/cache-poisoning/issue-642-repro.yml
This is an initial stab at exposing greater generality when evaluating whether a set of controls are "satisfied" for the purpose of considering an action enabled.
Doing this while also preserving the concept of "default enablement" results in some very wonky 4-valued logic, since there are 4 different states a control can evaluate to:
1. Satisfied by default
2. Satisfied through evaluation
3. Not satisfied through evaluation
4. "Conditional," i.e. we don't know because it's driven by an expression or similar
This is a little hard to follow, so I need to think about this more before actually merging it. However, the tests _do_ pass and I've also added a successful test for the original bug case that spurred this.
Fixes #642.
=> bugfix: cache-poisoning: fix false positive for docker/setup-buildx-action

Cargo.lock, Cargo.toml, docs/release-notes.md
=> bugfix: bump github-actions-models to 0.27.0

docs/release-notes.md, docs/snippets/help.txt, docs/usage.md, src/main.rs
This makes `--format=json` an alias for `json-v1`, giving me the flexibility to build a v2 JSON format at some point in the future. Also documents the compat policy for JSON format versions.
=> feat: add JSON format versioning

Cargo.lock, Cargo.toml, docs/release-notes.md, tests/integration/snapshot.rs, tests/integration/snapshots/integration__snapshot__unpinned_uses-5.snap, tests/integration/test-data/unpinned-uses/issue-659-repro.yml
This fixes #659 by bumping `yamlpath`, which in turn contains a fix for pathing behavior when a YAML
block sequence contains an interceding comment
between a sequence member and its body.
=> bugfix: bump yamlpath, fix #659

Dockerfile
This PR converts the Docker file from Debian to Wolfi.
`zizmor` is a first class Wolfi package and is automatically bumped to the newest version. This means that the build step (and `ZIZMOR_VERSION`) are unnecessary. Please let me know if you're interested in handling this differently: https://github.com/wolfi-dev/os/blob/main/zizmor.yaml
Unlike other distros, security is the top priority of Wolfi and contains zero CVEs. Here is a comparison between the suggested and current docker files using [grype](https://github.com/anchore/grype):
Suggested Wolfi-based Docker
```
[eslerm@ares zizmor]$ grype zizmor:demo
✔ Loaded image                                                                                           zizmor:demo 
✔ Parsed image …
```
=> ci: convert Dockerfile to Wolfi

docs/audits.md
Recommends https://github.com/GitHubSecurityLab/actions-permissions to make it easier for users to find the minimally required permissions. That might be easier for users than pure trial and error, or digging through the GitHub API documentation to find the needed permissions.
If you are aware of other tools which can do this, maybe it would be worth mentioning them as well.
:warning: That action is currently still in beta and has some [limitations](https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor#known-limitations), but maybe it is useful nonetheless.
=> docs: recommend GitHubSecurityLab/actions-permissions

src/github_api.rs
This isn't 100% ideal, since there's some duplication and _ideally_ I'd be able to propagate the `.context` as a "tip" instead, for prettier rendering. But it should hopefully clarify some existing confusion.
Closes #691.
=> feat: github_api: improve 403 errors slightly

tests/integration/common.rs, tests/integration/e2e.rs, tests/integration/snapshot.rs
In case of an error, this makes it easier to understand that execution failed, compared to the current behavior which is just an empty snapshot output.
=> tests: check zizmor exit code

src/audit/artipacked.rs, src/audit/bot_conditions.rs, src/audit/forbidden_uses.rs, src/audit/github_env.rs, src/audit/impostor_commit.rs, src/audit/insecure_commands.rs, src/audit/known_vulnerable_actions.rs, src/audit/obfuscation.rs, src/audit/ref_confusion.rs, src/audit/template_injection.rs, src/audit/unpinned_uses.rs, src/audit/use_trusted_publishing.rs, src/models.rs, src/models/coordinate.rs
I noticed that multiple audit rules were handling `audit_step` and `audit_composite_step`, but previously their code was duplicated.
Therefore I tried to deduplicate it now. As part of that I also tried to make the `use` declarations a bit more consistent.
Hopefully I did not overlook something. Feedback is appreciated!
=> feat: reduce code duplication for workflow step handling

tests/integration/common.rs, tests/integration/e2e.rs
- `e2e::invalid_config_file`
Was previously failing because `/dev/null` does not exist on Windows. Have used `NUL` now for Windows.
```
error: failed to load config: The system cannot find the path specified. (os error 3)
```
- `e2e::menagerie`
Was previously failing because the expected snapshot output contains the file path separator `/`, but on Windows it is `\`. Have added replacement logic.
Not sure if these changes are clean enough, or if they could be simplified. Feedback is appreciated!
`e2e::color_control_tty` and `e2e::progress_bar_tty` still fail for me because I don't have `unbuffer`. It seems there are [workarounds for Windows](https://stackoverflow.com/q/11516258) but I haven't tried this yet.
=> bugfix: fix e2e test failures on Windows

docs/usage.md
This makes the example `zizmor` workflow consistent with `zizmor`'s own default policies.
=> chore(docs): hash-pin setup-uv in usage.md

src/audit/artipacked.rs, src/audit/bot_conditions.rs, src/audit/cache_poisoning.rs, src/audit/dangerous_triggers.rs, src/audit/excessive_permissions.rs, src/audit/forbidden_uses.rs, src/audit/github_env.rs, src/audit/hardcoded_container_credentials.rs, src/audit/impostor_commit.rs, src/audit/insecure_commands.rs, src/audit/known_vulnerable_actions.rs, src/audit/mod.rs, src/audit/obfuscation.rs, src/audit/overprovisioned_secrets.rs, src/audit/ref_confusion.rs, src/audit/secrets_inherit.rs, src/audit/self_hosted_runner.rs, src/audit/template_injection.rs, src/audit/unpinned_uses.rs, src/audit/unredacted_secrets.rs, src/audit/use_trusted_publishing.rs, src/finding/mod.rs, src/models.rs, src/models/coordinate.rs, src/output/plain.rs, src/utils.rs
Follow-up for #697
I was able to implement this now by having the new `document()` method return `&'s yamlpath::Document`[^1] instead of `&'s impl AsRef<yamlpath::Document>`, since for the latter the Rust compiler wanted explicit lifetimes at the callsites of `document()`, and I could not get that to work.
(Though if you know a way to make this work with `impl AsRef<...>` or similar, that would probably be even better.)
[^1]: Actually using  `&'s yamlpath::Document` was suggested by Copilot, though it still need some manual work to make it compile. Maybe it just chose the more straight forward approach without really understanding the effects, and I was just so fixated on using `impl AsRef<...>`.
=> feat: further reduce step handling code duplication

src/models.rs
These are never accesses directly, and should always be accessed via the `AsDocument` trait.
=> chore: models: remove pub(crate) from some fields

docs/release-notes.md, src/output/sarif.rs
This changes the SARIF rule ID to `zizmor/{id}` and adds a name to each rule descriptor, since not all tools fall back to the ID (specifically, VS Code's SARIF viewer appears to fail to do this).
Closes #622.
Fixes #709.
=> bugfix: sarif: prefix ID, add rule names

src/audit/known_vulnerable_actions.rs, src/github_api.rs
Since recent changes `longest_tag_for_commit` already adds the error context (`with_context(...)`) itself, see https://github.com/woodruffw/zizmor/pull/713/commits/06f8f51b5a215f9446c2e14b3cf98448f578976d.
=> chore: remove duplicate context

docs/release-notes.md, src/github_api.rs, tests/integration/e2e.rs, tests/integration/snapshots/integration__e2e__issue_726.snap
This ensures that we correctly collect an action
defined under `.github/workflows/`, e.g.
`<repo>/.github/workflows/my-action/action.yml`.
This isn't a very common thing to do, but it's
perfectly valid from GitHub's perspective.
~~Needs tests. I need to think about a good way to test this.~~
Fixes #726.
=> bugfix: fix edge case in remote audit input collection

docs/audits.md, src/audit/unpinned_images.rs, tests/integration/snapshot.rs, tests/integration/snapshots/integration__e2e__issue_569.snap, tests/integration/snapshots/integration__snapshot__unpinned_images.snap
Pedantic findings are emitted by the unpinned-images audit when it encounters OCI image references that use a tag other than `latest`.
The pedantic finding is resolved, will not be produced when the image reference uses a SHA256 hash rather than a tag.
This closes #736
=> feat: emit pedantic finding for tagged OCI images

src/audit/obfuscation.rs, src/expr/mod.rs, tests/integration/snapshots/integration__e2e__issue_569.snap, tests/integration/snapshots/integration__snapshot__obfuscation.snap, tests/integration/test-data/obfuscation.yml
Index expressions can contain calls, etc.,
which themselves are constant reducible.
Also renamed everything from "constant foldable" to "constant reducible" since "foldable" means something specific that we're doing a superset of.
=> feat: handle reducible index subexpressions

src/audit/cache_poisoning.rs, src/models/coordinate.rs, src/models/uses.rs
These were half-baked and overlapped entirely with `RepositoryUsesPattern`.
=> refactor: remove old repo matching APIs

crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-10.snap, crates/zizmor/tests/integration/test-data/template-injection/issue-749-repro.yml, docs/release-notes.md
This adds a test for #749, which was fixed in #800.
=> test: add test for #749

.github/dependabot.yml, .github/workflows/pinact.yml, docs/audits.md
The idea here is to replace our use of Dependabot with `pinact`, since the latter allows us to update arbitrary files (including our documentation).
=> chore(ci): experiment with pinact

Cargo.lock, Cargo.toml, crates/zizmor/Cargo.toml, crates/zizmor/src/main.rs, crates/zizmor/src/models.rs, docs/release-notes.md, docs/snippets/help.txt
I'm packaging zizmor for Chimera Linux right now (see https://github.com/chimera-linux/cports/pull/4255), and Chimera Linux is shipping nushell completions where available. As a nushell user, I'd love to see nushell completions for zizmor in addition to the ones already provided. While I was at it, I also added carapace, which is a multi-shell completion engine.
The way I'm doing it here is not great, because it requires replicating `clap_complete::Shell` and extending it to support the additional shells. An alternative that requires less code on the zizmor side is to use something like `clap_allgen`, but that is not intended to be used with a `Shell` enum, it's intended use is to generate all completions with one function call. Going for that would be a breaking change of the CLI …
=> feat(cli): add completion generation support for nushell

Cargo.lock, Cargo.toml, crates/github-actions-models/Cargo.toml, crates/github-actions-models/src/common.rs, crates/zizmor/src/audit/insecure_commands.rs, crates/zizmor/tests/integration/e2e.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__insecure_commands-2.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__insecure_commands-3.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__insecure_commands-4.snap, crates/zizmor/tests/integration/test-data/insecure-commands.yml, crates/zizmor/tests/integration/test-data/insecure-commands/action.yml, crates/zizmor/tests/integration/test-data/insecure-commands/issue-839-repro.yml, docs/release-notes.md
TL;DR: We previously (incorrectly) treated any nonempty string as a "true" value for `insecure-commands`, when in reality the GitHub Actions runner uses C#'s `Boolean.TryParse` for this.
We fix our handling by reproducing `Boolean.TryParse`'s behavior.
Fixes #839.
=> fix: handle booleans for insecure-commands correctly

docs/installation.md
With https://github.com/chimera-linux/cports/pull/4255 merged, zizmor is now being built for Chimera Linux and Chimera Linux users will be able to install it from there, so I thought I'd update the docs.
How do the icons work? I've looked around and couldn't really find where they are sourced from.
=> docs: describe installation of Chimera Linux package

.github/workflows/codegen.yml, Makefile, crates/zizmor/build.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-11.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-12.snap, crates/zizmor/tests/integration/test-data/template-injection/codeql-sinks.yml, crates/zizmor/tests/integration/test-data/template-injection/pwsh-script.yml, docs/release-notes.md, pyproject.toml, support/codeql-injection-sinks.json, support/codeql-injection-sinks.py, uv.lock
Closes #743.
Closes #417.
TODOs:
=> feat: add CodeQL injection sink data

docs/usage.md
Closes #855 
This creates two small changes to the docs on usage.  One explicitly states the permissions needed for `GH_TOKEN`.  The other adds an example of passing in the [GitHub CLI's](https://cli.github.com) token instead of using a long-lived personal access token.
=> Update usage directions to explicitly state permissions needed

crates/zizmor/src/main.rs, docs/release-notes.md
While using zizmor at work today I noticed that when specifying `--gh-hostname` and failing to collect inputs from an on-prem GitHub Enterprise Server, zizmor would emit a message making it seem like it was trying to connect to github.com.
=> fix: update error message to handle enterprise servers

Cargo.lock, Cargo.toml, crates/github-actions-expressions/Cargo.toml
Revealed during a failed dry-run of #877.
=> chore: release github-actions-expressions 0.0.4

.github/workflows/zizmor.yml, Cargo.lock, Cargo.toml, crates/github-actions-models/Cargo.toml, crates/github-actions-models/src/action.rs, crates/github-actions-models/src/workflow/job.rs, crates/github-actions-models/tests/test_workflow.rs, crates/zizmor/src/audit/insecure_commands.rs, crates/zizmor/src/models.rs, crates/zizmor/src/models/coordinate.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-13.snap, crates/zizmor/tests/integration/test-data/template-injection/issue-883-repro/action.yml, docs/release-notes.md
This fixes #883 by removing the `panic!` case entirely -- it's not actually needed, since `uses:` steps can contain `env:` blocks.
Fixes #883.
=> fix: remove spurious panic in env handling

docs/assets/chips.css, docs/usage.md, mkdocs.yml
Documents `zizmorcore/zizmor-action` now that it's meant for public use.
=> docs: mention zizmorcore/zizmor-action

crates/github-actions-expressions/src/lib.rs, crates/zizmor/src/audit/bot_conditions.rs, crates/zizmor/src/models.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__bot_conditions.snap, crates/zizmor/tests/integration/test-data/bot-conditions.yml, docs/release-notes.md
~~WIP.~~
https://boostsecurity.io/blog/weaponizing-dependabot-pwn-request-at-its-finest made me realize that there were a couple of contexts we weren't checking for properly. 
Separately, this also switches `bot-conditions` to use our context pattern APIs (so that we handle more varieties of contexts, like index-style contexts) and begins the work to ensure we handle numeric actor ID checks as well.
=> feat: improve bot-conditions checks

docs/assets/chips.css, docs/usage.md
Decompose a bit, and switch to a ZWSP for the dummy element to prevent a visual space from sneaking in and throwing the alignment off.
=> chore(docs): tweak chip rendering

crates/github-actions-expressions/src/expr.pest, crates/github-actions-expressions/src/lib.rs, docs/release-notes.md
This prevents us from accidentally matching
shorter variants first, leading to parse errors.
Fixes #912.
=> bugfix: put longer comp_op variants ahead

crates/github-actions-expressions/src/context.rs, crates/zizmor/src/audit/bot_conditions.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/models.rs, crates/zizmor/src/models/coordinate.rs, crates/zizmor/src/utils.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-5.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-7.snap, docs/release-notes.md
We need to do this for two reasons:
1. It makes the patches smaller;
2. It's technically more correctly, since the GHA runner's values for these variables always take precedence anyways (at least, according to GitHub's docs).
For (2):
> You can't overwrite the value of the default environment variables named GITHUB_* and RUNNER_*. Currently you can overwrite the value of the CI variable. However, it's not guaranteed that this will always be possible. For more information about setting environment variables, see [Defining environment variables for a single workflow](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#defining-environment-variables-for-a-single-workflow) and [Workflow commands for GitHub …
=> feat: handle default envvars when fixing template injections

crates/github-actions-expressions/src/context.rs, crates/github-actions-models/src/workflow/event.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/models.rs, crates/zizmor/src/models/action.rs, crates/zizmor/src/models/coordinate.rs, crates/zizmor/src/models/inputs.rs, crates/zizmor/src/models/workflow.rs, crates/zizmor/src/utils.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-13.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-8.snap, crates/zizmor/tests/integration/test-data/template-injection/input-caps.yml
~~WIP.~~
This adds a `HasInputs` trait that allows workflow and action inputs to be queried for capability, similar to how other contexts can be queried for capabilities via the FST.
The ultimate idea here is to plug this into `template-injection` so that expansions of `input.*` contexts can be evaluated more accurately.
=> feat: model input capabilities in workflows and actions

Cargo.lock, Cargo.toml, crates/yamlpath/Cargo.toml, crates/yamlpath/src/lib.rs, crates/zizmor/src/yaml_patch/mod.rs
This renames some tests and removes the need for a `handle_root_level_addition` special-case in `Op::Add` by reusing the existing codepaths. It also adds a test to ensure that `Op::Add` fails when the key already exists in the targeted mapping.
=> chore: remove a root level special case

crates/zizmor/src/yaml_patch/mod.rs
Renames a bunch of tests to generally match the `test_{op}_*` pattern, for easier searching.
=> chore(tests): rename tests for consistency

crates/zizmor/src/audit/anonymous_definition.rs, crates/zizmor/src/audit/mod.rs, crates/zizmor/src/main.rs, crates/zizmor/tests/integration/acceptance.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__issue_569.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__issue_726.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__anonymous_definition-2.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__anonymous_definition.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__ref_confusion.snap, crates/zizmor/tests/integration/test-data/anonymous-definition.yml, docs/audits.md, docs/release-notes.md
Notes:
* GitHub UI being impacted by unnamed Workflows make severity feel higher for that than jobs. That said, since it is not a security problem, I felt like "Low" was appropriate. Curious thoughts on this.
* I left out 'ReusableWorkflowCallJob' since as far as I could tell, they did not have any naming capabilities
Closes: https://github.com/zizmorcore/zizmor/issues/795
=> feat: new audit: anonymous-definition

docs/usage.md
This example in the docs was deliberately using a ref pin (`@v3`) for the sake of demonstrating `unpinned-uses`, but it got fixed accidentally by #817.
It unfortunately seems like this is likely to happen again if `pinact` is run again. I don't know what the right long-term solution is.
=> docs: Unfix accidentally-fixed pinning example

crates/zizmor/src/registry.rs
This is a small QOL improvement for users attempting to debug `zizmor`'s behavior on one or more inputs.
xref #952, h/t @smillerdev
=> chore: add a debug message when registering inputs

Cargo.lock, crates/github-actions-models/Cargo.toml, crates/github-actions-models/src/common.rs, crates/github-actions-models/src/workflow/job.rs, crates/zizmor/src/main.rs, crates/zizmor/src/models/action.rs, crates/zizmor/src/models/workflow.rs, crates/zizmor/src/utils.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-10.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-2.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-3.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-4.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-5.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-6.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-7.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-8.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs-9.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__invalid_inputs.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__menagerie-2.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__menagerie.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-10.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-11.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-12.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-6.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-7.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-8.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__unpinned_uses-9.snap, docs/release-notes.md
The error in #952 now looks like this:
```
ERROR collect_inputs: github_actions_models::common: msg="repo action must have `@<ref>` in reusable workflow"
fatal: no audit was performed
failed to load input as Workflow
Caused by:
0: failed to load workflow from file://tmp.yml
1: couldn't turn input into a an appropriate model
2: this suggests a bug in zizmor; please report it!
3: jobs: data did not match any variant of untagged enum Job at line 23 column 3
```
Closes #952.
=> feat: better error messages for invalid inputs

crates/zizmor/src/audit/artipacked.rs, crates/zizmor/src/audit/mod.rs, crates/zizmor/src/main.rs, crates/zizmor/src/models/action.rs, crates/zizmor/tests/integration/e2e.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__pr_960_backstop.snap, crates/zizmor/tests/integration/test-data/pr-960-backstop/action.yml
I regressed this in a hard-to-notice way with #896.
Needs a good regression test; a non-composite test that doesn't cause a crash would probably be sufficient.
=> bugfix: eliminate a panic when auditing composite actions

crates/zizmor/src/audit/artipacked.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/finding.rs, crates/zizmor/src/fix.rs, crates/zizmor/src/registry.rs
This refactors `zizmor::fix` to use each `Fix::key` instead of trying to infer it from the parent `Finding`'s first location. In doing so we also save ourselves a handful of clones.
=> chore: refactor fix input key handling

Cargo.lock, Cargo.toml
=> chore(deps): bump http-cache-reqwest to 0.16.0

crates/zizmor/src/main.rs, crates/zizmor/src/state.rs
This is a halfway point towards #1010.
More accurately: this leaves things the way they are currently, but with a more "correct" error message when the user passes an empty string for an option.
=> bugfix(cli): forbid some empty values for options

crates/zizmor/src/audit/cache_poisoning.rs, crates/zizmor/src/audit/use_trusted_publishing.rs, crates/zizmor/src/models/coordinate.rs, crates/zizmor/src/utils.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-4.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__use_trusted_publishing.snap, crates/zizmor/tests/integration/test-data/use-trusted-publishing.yml
This generalizes the manual checks in `use-trusted-publishing` by lifting them into the `ActionCoordinate` pattern API. Doing this required some changes to how control fields are evaluated, plus a new `ControlExpr::Not` that allows us to write negative matches on fields.
Behaviorally, no breaking changes should come from this.
=> refactor: generalize use-trusted-publishing audit

.github/workflows/benchmark-base.yml, .github/workflows/benchmark-pr-1p.yml, Makefile, bench/.gitignore, bench/benchmark.py, bench/benchmarks.json
WIP.
This adds `benchmark.py`, which is essentially just a bit of instrumentation around `hyperfine` and benchmark planning/execution (including input setup).
It's a little bit overkill, but the thinking behind it is that it'll give me a decent foundation to add more benchmarks in the future, plus gives me structured output (JSON files in `bench/results`). For the latter, I'm going to evaluate [bencher.dev](https://bencher.dev/).
=> feat: CLI benchmarking harness

crates/zizmor/src/audit/template_injection.rs, crates/zizmor/tests/integration/test-data/template-injection/addnab-docker-run-action.yml, docs/release-notes.md
`addnab/docker-run-action` has (at least) two relevant sinks: `run` obviously runs code, while `options` runs it less obviously (the flags aren't validated, so someone could inject a different image than expected).
=> feat: another template injection sink

crates/zizmor/src/audit/github_env.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/audit/use_trusted_publishing.rs, crates/zizmor/src/models.rs, crates/zizmor/src/models/action.rs, crates/zizmor/src/models/workflow.rs, docs/release-notes.md
This PR fixes #1049 by detecting all the supported shells except Python and applying the correct environment variable syntax for fixing the finding(s), according to [GitHub workflow syntax](https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_iddefaultsrunshell).
=> Detect `shell` before applying template expression fixes

crates/zizmor/src/audit/known_vulnerable_actions.rs, crates/zizmor/src/audit/mod.rs, crates/zizmor/src/config.rs, crates/zizmor/src/lsp.rs, crates/zizmor/src/main.rs, crates/zizmor/tests/integration/config.rs, crates/zizmor/tests/integration/snapshots/integration__config__disablement.snap, crates/zizmor/tests/integration/test-data/config-scenarios/disablement/.github/workflows/hackme.yml, crates/zizmor/tests/integration/test-data/config-scenarios/disablement/zizmor.yml, docs/configuration.md, docs/release-notes.md
This adds `disable: <bool>` to per-audit configs, allowing audits to be disabled entirely on a per-group basis.
(I was previously uncomfortable with audit disablement and still am to some extent, but I'm convinced that there are legitimate engineering reasons why people want this. I've added some scary language to the docs emphasizing that most users shouldn't need this. I'm also more comfortable with this now that config is loaded on a per-group basis, since a user can't accidentally disable findings outside of a single group now.)
Closes #714. 
See also #1123.
=> feat: allow audits to be disabled in config

docs/audits.md, docs/release-notes.md
=> docs: document `ref-version-mismatch` audit

Cargo.lock, Cargo.toml, crates/zizmor/Cargo.toml, crates/zizmor/src/main.rs, docs/release-notes.md
I'm not sure how much of a boost this will be; we'll see.
=> perf: use jemalloc as the global allocator on non-Windows

crates/github-actions-models/tests/sample-workflows/rnpgp-rnp-centos-and-fedora.yml
This token was already breached upstream, but that's no reason for us to propagate it here.
I suspect it's also been copied into the crate packages for `github-actions-models`, since those include test cases.
Closes #1210.
=> github-actions-models: remove token from vendored testcase

crates/zizmor/src/audit/ref_version_mismatch.rs, crates/zizmor/src/main.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__ref_version_mismatch.snap, docs/release-notes.md
This PR adds auto-fix for ref-version-mismatch audit rule with online tests against GitHub API.
xref #876
=> Add Fix for ref-version-mismatch audit rule
