zizmorcore/zizmor

.github/workflows/zizmor.yaml
This is a ~copy of what's working for me in [keepachangelog-parser-java][1].
[1]: https://github.com/colindean/keepachangelog-parser-java/blob/master/.github/workflows/zizmor.yml
If accepted, this could probably be linked from README.md instead of the ESLint example link in #70.
=> Create workflow that runs zizmor latest

README.md
=> docs: add homebrew install

Cargo.lock, Cargo.toml
=> chore: prep 0.1.5

docs/audits.md, mkdocs.yml
Added more details on execution requirements for existing audits.
In addition, I added some bullets explaining what _"Works offline"_ and "_Enabled by Default"_  mean. I preferred to not add further explanations on those for every table, for the sake of avoid repetition and easier editing in the future.
[Example preview](https://github.com/woodruffw/zizmor/blob/c0b73e65a9b611a876b402c4e6eac728ebdc6459/docs/audits.md) (on Github)
Closes #47
=> docs: explains execution requirements for all available audits

Cargo.lock, Cargo.toml
=> chore: prep 0.1.6

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml
=> chore: add issue forms + config

Cargo.lock, Cargo.toml
Fixes https://github.com/woodruffw/zizmor/issues/109.
=> fix: bump github-actions-models

src/config.rs, src/main.rs
Closes https://github.com/woodruffw/zizmor/issues/138.
=> feat: add `--no-config`

.github/workflows/ci.yml, Makefile, docs/configuration.md, docs/development.md, docs/quickstart.md, docs/snippets/help.txt, docs/usage.md, mkdocs.yml
Adds a `help.txt` snippet containing `zizmor --help`. ~~I need to set up a CI job that ensures that remains up-to-date.~~
=> docs: misc improvements

.github/ISSUE_TEMPLATE/feature-request.yml, src/render.rs
Adds zero information to the output.
Fixes #147.
=> feat(cli): don't render "0 ignored"

src/render.rs
=> fix(cli): remove '0 ignored' from another place

docs/audits.md, mkdocs.yml, src/audit/impostor_commit.rs, src/audit/known_vulnerable_actions.rs, src/audit/mod.rs, src/audit/ref_confusion.rs, src/audit/unpinned_uses.rs, src/main.rs, src/models.rs, tests/acceptance.rs, tests/test-data/unpinned-uses.yml
=> feat: unpinned-uses audit

.github/release.yml
This will make our release notes slightly prettier.
=> chore: add release categories

docs/audits.md, mkdocs.yml
~~WIP.~~ The plan here is to rewrite the current audit docs to use fewer subheadings, and include remediation examples.
=> docs: rewrite audit docs

README.md, docs/index.md, docs/installation.md
=> docs: more badges

docs/audits.md, docs/development.md
=> docs: adds recommentations on how to add or change audits

docs/usage.md
=> docs: document ignore comments

Cargo.lock, Cargo.toml, docs/usage.md, src/finding/locate.rs, src/finding/mod.rs
=> feat: generalized ignore comments

Cargo.toml, README.md, docs/index.md, docs/snippets/help.txt
Lean a bit more into "static analysis," to avoid confusion about what zizmor can and can't do (e.g. running workflows).
=> chore: tweak zizmor's self-description

Cargo.lock
=> chore: `cargo update`

src/audit/github_env.rs, src/models.rs
~~WIP; incomplete.~~
This is a step towards handling `run:` bodies more generally.
=> feat: add Step::default_shell

src/audit/github_env.rs
`sh` is a valid `shell:` option ([source](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunshell)), and can be handled as the bash grammar is a superset.
=> feat: handle `shell: sh` in github-env

tests/snapshot.rs
This makes writing snapshot tests slightly more fluent.
=> test: refactor snapshot helper

docs/installation.md
Switches things to a content tab layout.
=> docs: tweak installation layout

Cargo.toml
Adds a couple of small missing things.
=> chore: add more metadata to Cargo.toml

src/audit/template_injection.rs
These are not attacker controllable.
h/t @alex
=> fix: template-injection: ignore issue/PR numbers

docs/trophy-case.md, mkdocs.yml
Closes #235.
As some point I should turn this list into a grid or some kind of other nice render.
=> docs: add a trophy case

.pre-commit-hooks.yaml, docs/usage.md
CCing @graingert to sanity-check me here -- I _think_ this is right now that the new repo exists.
=> docs: update pre-commit docs to point to new repo

.github/workflows/zizmor.yml
=> ci: make zizmor.yml very fast with uvx

src/audit/template_injection.rs
=> fix: template-injection: ignore runner.temp

src/audit/self_hosted_runner.rs, tests/snapshot.rs, tests/snapshots/snapshot__self_hosted-8.snap, tests/test-data/self-hosted/issue-283-repro.yml
A tentative fix for #283 
Added both the repro Workflow and the snapshot test to get us covered!
=> fix: dont crash when an expression does not expand a matrix

Cargo.lock, Cargo.toml
=> chore: prep 0.9.1

docs/snippets/trophies.md, docs/snippets/trophies.txt
=> docs: more trophies

src/sarif.rs
=> fix: sarif: use ResultKind for kind

src/sarif.rs
Track https://github.com/psastras/sarif-rs/pull/770 in source.
=> chore: add a TODO

docs/audits.md, src/audit/insecure_commands.rs, tests/snapshot.rs, tests/snapshots/snapshot__insecure_commands-3.snap, tests/test-data/insecure-commands/action.yml
=> feat: insecure-commands: support composite actions

Cargo.lock, Cargo.toml
=> deps: bump yamlpath

docs/installation.md
=> docs: installation: add badges

Cargo.lock, Cargo.toml, docs/release-notes.md
Fixes #387 by landing woodruffw/github-actions-models#28.
=> deps: bump github-actions-models

docs/snippets/render-trophies.py, docs/snippets/trophies.md, docs/snippets/trophies.txt
Mash trophies in the same org together.
=> docs: compress trophies

docs/usage.md
=> docs: usage: clarify optional configuration

docs/snippets/trophies.md, docs/snippets/trophies.txt
=> docs: update trophies

.github/workflows/ci.yml, docs/release-notes.md, src/models.rs, tests/snapshot.rs, tests/snapshots/snapshot__template_injection-7.snap, tests/test-data/template-injection/issue-418-repro.yml
Fixes #418, which manifests as a crash.
=> fix: template-injection: do not fail on `uses:` steps

docs/release-notes.md, src/audit/template_injection.rs
See #417. There's a lot more to do here, most of which we should probably automatically extract from GitHub's hard work.
=> feat: template-injection: handle 2 more sinks

docs/usage.md
=> docs: fix formatting

src/audit/cache_poisoning.rs, src/models/coordinate.rs
This is a slightly more obvious name for this type.
=> refactor: UsesCoordinate -> ActionCoordinate

docs/release-notes.md, src/audit/unpinned_uses.rs, tests/snapshot.rs, tests/snapshots/snapshot__unpinned_uses-4.snap, tests/test-data/unpinned-uses/issue-433-repro.yml
=> fix: don't flag local workflows in unpinned-uses

docs/snippets/trophies.md, docs/snippets/trophies.txt
=> docs: bump trophies

docs/release-notes.md, src/audit/artipacked.rs, tests/snapshot.rs, tests/snapshots/snapshot__artipacked-4.snap, tests/test-data/artipacked/issue-447-repro.yml
=> fix: artipacked: check for stringy bools

src/audit/artipacked.rs, src/audit/cache_poisoning.rs, src/audit/excessive_permissions.rs, src/audit/github_env.rs, src/audit/hardcoded_container_credentials.rs, src/audit/impostor_commit.rs, src/audit/insecure_commands.rs, src/audit/mod.rs, src/audit/ref_confusion.rs, src/audit/secrets_inherit.rs, src/audit/self_hosted_runner.rs, src/audit/template_injection.rs, src/config.rs, src/finding/mod.rs, src/main.rs, src/models.rs, src/models/coordinate.rs, src/registry.rs, src/render.rs
This eliminates a bunch of invalid states in the job APIs via better typing.
=> refactor: reduce invalid states in job APIs

docs/snippets/trophies.md, docs/snippets/trophies.txt
=> chore(docs): bump trophies

Makefile, README.md, docs/index.md, docs/snippets/render-sponsors.py, docs/snippets/sponsors.html, docs/snippets/sponsors.json
Many thanks to @astral-sh / @charliermarsh for being the first logo sponsor!
=> docs: add sponsors to README and site

.github/workflows/pypi.yml, docs/release-notes.md
~~WIP, don't know if this works yet.~~
Fixes #455.
=> ci: pypi: try enabling aarch64 on an ARM runner

Cargo.lock, Cargo.toml, docs/release-notes.md
=> bugfix: bump github-actions-models

Cargo.lock, Cargo.toml, docs/release-notes.md, docs/usage.md
=> chore: prep 1.2.0

src/main.rs
Took me three months to remember to do this!
Fixes #43.
h/t @miketheman
=> cli: reduce warning to info when skipping audits

docs/release-notes.md, src/main.rs, src/render.rs
=> feat(cli): add naches mode

docs/development.md
=> docs: update dev-docs

docs/release-notes.md, src/expr/expr.pest, src/expr/mod.rs
=> bugfix: expr: make index rule non-atomic

docs/release-notes.md, src/finding/mod.rs, src/sarif.rs
~~WIP.~~
This jumps through the requisite hoops to make our output within GitHub's SARIF viewer slightly better.
Closes #526.
=> feat: improve SARIF comprehension on GitHub

.github/workflows/docker.yml, docs/installation.md
Also document the image in the installation guide.
=> chore: add latest tag to Docker image builds

docs/release-notes.md, src/audit/bot_conditions.rs, tests/snapshots/snapshot__bot_conditions.snap
=> feat: bot-conditions: check github.triggering_actor

Cargo.lock, Cargo.toml, docs/release-notes.md, docs/usage.md
=> chore: prep for 1.4.0 release

Cargo.lock, Cargo.toml, docs/release-notes.md, docs/usage.md
Just to land https://github.com/woodruffw/zizmor/pull/566.
=> chore: prep 1.4.1 release

docs/release-notes.md, src/audit/template_injection.rs
=> bugfix: add `github.event.pull_request.head.sha` as a safe context

docs/usage.md
CC @ncoghlan for thoughts on whether this language/docs location makes sense!
Fixes #625.
=> docs: add a callout about SARIF exit code behavior

Cargo.lock, Cargo.toml, docs/release-notes.md
=> bugfix: bump github-actions-models to 0.28.0

docs/audits.md, src/audit/forbidden_uses.rs, src/audit/mod.rs, src/audit/unpinned_uses.rs, src/main.rs, src/models/uses.rs, test-config.yml, tests/integration/snapshot.rs, tests/integration/snapshots/integration__e2e__gha_hazmat.snap, tests/integration/snapshots/integration__e2e__issue_569.snap, tests/integration/snapshots/integration__e2e__menagerie-2.snap, tests/integration/snapshots/integration__e2e__menagerie.snap, tests/integration/snapshots/integration__snapshot__forbidden_uses-2.snap, tests/integration/snapshots/integration__snapshot__forbidden_uses-3.snap, tests/integration/snapshots/integration__snapshot__forbidden_uses-4.snap, tests/integration/snapshots/integration__snapshot__forbidden_uses.snap, tests/integration/snapshots/integration__snapshot__unpinned_uses-10.snap, tests/integration/snapshots/integration__snapshot__unpinned_uses-7.snap, tests/integration/snapshots/integration__snapshot__unpinned_uses-8.snap, tests/integration/snapshots/integration__snapshot__unpinned_uses-9.snap, tests/integration/test-data/forbidden-uses/configs/allow-all.yml, tests/integration/test-data/forbidden-uses/configs/allow-some.yml, tests/integration/test-data/forbidden-uses/configs/deny-all.yml, tests/integration/test-data/forbidden-uses/configs/deny-some.yml, tests/integration/test-data/forbidden-uses/forbidden-uses-menagerie.yml
Building up from #574.
TODO:
Closes #558.
=> feat: new audit: forbidden-uses

docs/release-notes.md, src/audit/template_injection.rs, tests/integration/snapshot.rs, tests/integration/snapshots/integration__snapshot__template_injection-9.snap, tests/integration/test-data/template-injection/false-positive-menagerie.yml
See https://github.com/woodruffw/zizmor/discussions/673.
=> bugfix: template-injection: mark another context as safe

docs/audits.md, src/audit/unpinned_uses.rs, src/models/uses.rs, tests/integration/snapshot.rs, tests/integration/snapshots/integration__snapshot__unpinned-uses-composite-config-2.snap, tests/integration/snapshots/integration__snapshot__unpinned-uses-composite-config.snap, tests/integration/snapshots/integration__snapshot__unpinned-uses-empty-config.snap, tests/integration/snapshots/integration__snapshot__unpinned-uses-hash-pin-everything-config.snap, tests/integration/snapshots/integration__snapshot__unpinned_uses-10.snap, tests/integration/snapshots/integration__snapshot__unpinned_uses-7.snap, tests/integration/snapshots/integration__snapshot__unpinned_uses-8.snap, tests/integration/snapshots/integration__snapshot__unpinned_uses-9.snap, tests/integration/test-data/unpinned-uses/configs/composite-2.yml, tests/integration/test-data/unpinned-uses/menagerie-of-uses.yml
Having done this, I now feel less confident that this makes sense vs. just exposing a `fnmatch` compatible pattern syntax. However that would probably be too flexible.
TODO: 
Fixes #669.
=> feat: generalize RepositoryUsesPattern

docs/audits.md
=> chore(docs): clarify default rule in explicit config

docs/audits.md, docs/release-notes.md, src/audit/mod.rs, src/audit/obfuscation.rs, src/audit/overprovisioned_secrets.rs, src/audit/unredacted_secrets.rs, src/expr/mod.rs, src/main.rs, tests/integration/snapshot.rs, tests/integration/snapshots/integration__e2e__issue_569.snap, tests/integration/snapshots/integration__snapshot__obfuscation.snap, tests/integration/test-data/obfuscation.yml
~~WIP; needs to be fleshed out more.~~
TODO:
Closes #458
=> feat: new audit: obfuscation

docs/audits.md, docs/release-notes.md, src/audit/mod.rs, src/audit/stale_action_refs.rs, src/github_api.rs, src/main.rs, tests/integration/common.rs, tests/integration/snapshot.rs, tests/integration/snapshots/integration__e2e__gha_hazmat.snap, tests/integration/snapshots/integration__e2e__issue_569.snap, tests/integration/snapshots/integration__e2e__menagerie-2.snap, tests/integration/snapshots/integration__e2e__menagerie.snap, tests/integration/snapshots/integration__snapshot__stale_action_refs.snap, tests/integration/test-data/stale-action-refs.yml
=> feat: new audit: stale-action-refs

.github/workflows/refresh-schemas.yml
=> chore(ci): add refresh-schemas workflow

docs/development.md
See https://github.com/woodruffw/zizmor/pull/716#issuecomment-2839617650
=> doc: mention insta `--force-update-snapshots`

docs/audits.md
=> chore(docs): put examples in example blocks

docs/release-notes.md, src/audit/unpinned_uses.rs, src/models/uses.rs, tests/integration/snapshot.rs, tests/integration/snapshots/integration__snapshot__forbidden_uses-5.snap, tests/integration/snapshots/integration__snapshot__forbidden_uses-6.snap, tests/integration/snapshots/integration__snapshot__unpinned_uses-12.snap, tests/integration/test-data/forbidden-uses/configs/allow-some-refs.yml, tests/integration/test-data/forbidden-uses/configs/deny-some-refs.yml, tests/integration/test-data/unpinned-uses/configs/invalid-policy-syntax-6.yml
=> feat: extend RepositoryUsesPattern to allow exact ref patterns

src/audit/bot_conditions.rs, src/audit/unredacted_secrets.rs, src/audit/unsound_contains.rs, src/expr/mod.rs
Make a field private; add some more tests.
=> chore: cleanup

Cargo.lock, Cargo.toml, docs/snippets/help.txt, docs/usage.md, src/main.rs
=> feat: tab completion

.github/workflows/zizmor.yml, docs/usage.md
This addresses a pedantic-only finding.
=> chore(docs): constrain permissions in workflow example

docs/release-notes.md, docs/snippets/help.txt, docs/usage.md, src/main.rs
=> feat: add ZIZMOR_CONFIG

docs/configuration.md
=> chore(docs): add env to config precedence

Makefile
=> build: fix paths in refresh-schemas target

Cargo.lock, Cargo.toml, crates/github-actions-expressions/Cargo.toml, crates/github-actions-expressions/README.md
=> chore(docs): give github-actions-expressions a README

crates/github-actions-expressions/src/context.rs, crates/github-actions-expressions/src/lib.rs, crates/zizmor/src/audit/bot_conditions.rs, crates/zizmor/src/audit/overprovisioned_secrets.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/audit/unredacted_secrets.rs, crates/zizmor/src/audit/unsound_contains.rs
=> feat: add ContextPattern APIs

.github/workflows/ci.yml, .github/workflows/docker.yml, .github/workflows/pypi.yml, .github/workflows/release-crate.yml, .github/workflows/release.yml, .github/workflows/site.yml, .github/workflows/test-output.yml, .github/workflows/zizmor.yml
Trialling https://github.com/zizmorcore/zizmor-action.
=> chore(ci): bump actions, use zizmor-action

.github/pinact.yml, .github/workflows/zizmor.yml, Makefile, docs/audits.md, docs/usage.md
Do everything locally. I'll complement this with a periodic issue-filing workflow, probably.
=> chore: add pinact, apply pinact

.cargo/config.toml, .github/workflows/release-binaries.yml, support/archive-release.sh
=> ci: experiment with a binary release build

Cargo.lock, crates/zizmor/Cargo.toml
This will hopefully exercise all of the recent build changes I've made.
=> chore: prep prerelease v1.8.0-rc0

.github/workflows/release-binaries.yml, Cargo.lock, Cargo.toml, crates/zizmor/Cargo.toml
=> fix: don't use wildcards for in-workspace deps

.github/workflows/release-binaries.yml, Cargo.lock, crates/zizmor/Cargo.toml
=> fix(ci): tell gh release upload where to go

docs/installation.md
=> docs: mention GitHub release binaries

mkdocs.yml
=> chore(docs): update org for shortcut links

docs/usage.md
Caught my eye while reading docs. Not sure if the expectation was to have an example of usage or to finish a sentence; I've opted for a second option, but if you want me to add an example her (similar for JSON), let me know and I'll update.
=> chore(docs): swap colon to dot

docs/installation.md
=> docs: add alpine linux installation notes

docs/installation.md
=> chore(docs): fix typos

README.md, docs/snippets/render-sponsors.py, docs/snippets/sponsors.html, docs/snippets/sponsors.json
=> chore(docs): update sponsors

.github/workflows/ci.yml, Cargo.toml, crates/github-actions-expressions/Cargo.toml, crates/github-actions-models/Cargo.toml, crates/yamlpath/Cargo.toml, crates/zizmor/Cargo.toml
Hey there :wave: 
These are just a few small tweaks to CI/Cargo/Clippy that I thought you might find useful! See the individual commits for the motivation for each change.
=> chore(ci): Small improvements around linting

support/wolfi-update-check.sh
Was using the old version, not the new one.
=> chore(ci): fix version variable in wolfi-update-check.sh

crates/zizmor/src/audit/artipacked.rs, crates/zizmor/src/audit/cache_poisoning.rs, crates/zizmor/src/audit/dangerous_triggers.rs, crates/zizmor/src/audit/forbidden_uses.rs, crates/zizmor/src/audit/known_vulnerable_actions.rs, crates/zizmor/src/audit/mod.rs, crates/zizmor/src/audit/obfuscation.rs, crates/zizmor/src/audit/overprovisioned_secrets.rs, crates/zizmor/src/audit/stale_action_refs.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/audit/unpinned_uses.rs, crates/zizmor/src/audit/unredacted_secrets.rs, crates/zizmor/src/finding/location.rs, crates/zizmor/src/models.rs, crates/zizmor/src/models/coordinate.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-5.snap, crates/zizmor/tests/integration/test-data/artipacked/demo-action/action.yml, docs/release-notes.md
Also includes some refactoring to reduce the rats' nest of lifetimes introduced by one of my earlier PRs.
Per #350.
=> feat: artipacked now supported composite actions

crates/zizmor/Cargo.toml
h/t https://infosec.exchange/@raptor/114632478525791894
=> chore: add zizmor's crate to the security category

crates/zizmor/src/audit/use_trusted_publishing.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__use_trusted_publishing-2.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__use_trusted_publishing.snap, crates/zizmor/tests/integration/test-data/use-trusted-publishing/demo-action/action.yml, docs/release-notes.md
=> feat: support composite actions in use-trusted-publishing

crates/yamlpath/tests/testcases/flow.yml
Ensures we extract features correctly on some multi-line flow cases.
=> chore(tests): add more flow test cases

crates/github-actions-expressions/src/context.rs, crates/github-actions-expressions/src/lib.rs, crates/zizmor/src/audit/bot_conditions.rs, crates/zizmor/src/audit/overprovisioned_secrets.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/audit/unredacted_secrets.rs, crates/zizmor/src/audit/unsound_contains.rs, crates/zizmor/src/utils.rs
=> refactor: add spanning to expressions

README.md, crates/zizmor/src/main.rs, docs/snippets/help.txt, docs/snippets/sponsors.html, docs/snippets/sponsors.json
=> chore(cli): add --thanks

crates/github-actions-models/tests/sample-workflows/homebrew-core-dispatch-rebottle.yml
chore(workflows): update default branch for homebrew actions
---
update per default branch name changes
https://github.com/Homebrew/actions/pull/704
=> chore(tests): update default branch for homebrew actions

crates/github-actions-expressions/src/context.rs, crates/github-actions-expressions/src/expr.pest, crates/github-actions-expressions/src/lib.rs, crates/yamlpath/src/lib.rs, crates/yamlpath/tests/integration_test.rs, crates/yamlpath/tests/testcases/flow.yml, crates/yamlpath/tests/testcases/key-only-features.yml, crates/zizmor/src/audit/bot_conditions.rs, crates/zizmor/src/audit/overprovisioned_secrets.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/audit/unsound_contains.rs, crates/zizmor/src/finding/location.rs, crates/zizmor/src/models/action.rs, crates/zizmor/src/models/workflow.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__bot_conditions.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__github_output.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-11.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-12.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-13.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-14.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-2.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-4.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-5.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-6.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-8.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection.snap, crates/zizmor/tests/integration/test-data/template-injection/multiline-expression.yml, docs/release-notes.md
=> template-injection: add subfeatures

crates/zizmor/src/audit/artipacked.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/finding.rs, crates/zizmor/src/main.rs, crates/zizmor/src/output/fix.rs, crates/zizmor/src/output/plain.rs, crates/zizmor/src/registry.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__gha_hazmat.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-2.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-3.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-4.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked-5.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__artipacked.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-2.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-4.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-5.snap, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-8.snap, docs/assets/chips.css, docs/snippets/help.txt, docs/usage.md
=> refactor: prepare fix mode for a public experimental release

Cargo.lock, Cargo.toml, crates/zizmor/src/github_api.rs
=> chore(deps): bump http-cache-reqwest to 0.15.2

Cargo.lock, Cargo.toml, crates/github-actions-expressions/src/lib.rs, crates/zizmor/Cargo.toml, crates/zizmor/src/finding/location.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__template_injection-15.snap, crates/zizmor/tests/integration/test-data/template-injection/issue-988-repro.yml, docs/release-notes.md
=> bugfix: repro,  #988

.github/workflows/release-support-crate.yml, .github/workflows/release-zizmor-crate.yml
=> chore(ci): add environments to crates.io workflows

.github/workflows/release-support-crate.yml, Cargo.lock, Cargo.toml, crates/github-actions-expressions/Cargo.toml
=> chore(ci): try using TP for support crates

Cargo.lock, crates/zizmor/Cargo.toml
=> chore: prep for 1.11.1-rc1 release

crates/zizmor/src/audit/github_env.rs
Now that I have benchmarks, maybe they'll reveal
whether this was a good idea or not.
=> refactor: remove RwLock from github-env audit

docs/development.md
- **chore(docs): update some dev instructions**
- **chore(docs): document the benchmarking components**
=> chore(docs): improve the dev docs a bit

crates/github-actions-expressions/src/lib.rs, crates/zizmor/src/audit/bot_conditions.rs, crates/zizmor/src/audit/mod.rs, crates/zizmor/src/audit/obfuscation.rs, crates/zizmor/src/audit/overprovisioned_secrets.rs, crates/zizmor/src/audit/template_injection.rs, crates/zizmor/src/audit/unredacted_secrets.rs, crates/zizmor/src/audit/unsound_condition.rs, crates/zizmor/src/audit/unsound_contains.rs, crates/zizmor/src/models/action.rs, crates/zizmor/src/models/workflow.rs, crates/zizmor/src/registry.rs, crates/zizmor/src/utils.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__unsound_condition.snap, crates/zizmor/tests/integration/test-data/unsound-condition.yml, docs/audits.md, docs/release-notes.md
=> feat: new audit: unsound-condition

crates/zizmor/src/audit/template_injection.rs, docs/release-notes.md
=> fix: fix overcorrected env patch for template-injection

crates/zizmor/src/audit/cache_poisoning.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__cache_poisoning-16.snap, crates/zizmor/tests/integration/test-data/cache-poisoning/issue-1081-repro.yml, docs/release-notes.md
=> fix: flip setup-uv coordinate toggle

docs/configuration.md
=> Document that composite action findings can be ignored with comments

docs/usage.md
See: https://github.com/orgs/zizmorcore/discussions/1099
=> Document that json-v1 uses 0-based line numbers

docs/audits.md
=> fix(docs): fix misleading dangerous-triggers docs

crates/zizmor/src/github_api.rs, crates/zizmor/src/registry/input.rs, crates/zizmor/tests/integration/e2e.rs, crates/zizmor/tests/integration/snapshots/integration__e2e__issue_1116_strict_collection_remote_input-2.snap, crates/zizmor/tests/integration/snapshots/integration__e2e__issue_1116_strict_collection_remote_input.snap, docs/release-notes.md
=> fix: respect --strict-collection for remote inputs

crates/zizmor/tests/integration/snapshots/integration__snapshot__unsound_condition.snap, crates/zizmor/tests/integration/test-data/unsound-condition.yml
=> chore(tests): add testcases for #742

crates/github-actions-expressions/src/lib.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__obfuscation-3.snap, crates/zizmor/tests/integration/test-data/obfuscation/issue-1177-repro.yml, docs/release-notes.md
=> fix(obfuscation): don't consider fromJSON(...) constant-reducible

Cargo.lock, Cargo.toml, crates/zizmor/Cargo.toml, crates/zizmor/src/lsp.rs
=> deps: move from tower-lsp to tower-lsp-server

crates/zizmor/src/audit/dependabot_execution.rs, crates/zizmor/src/audit/mod.rs, crates/zizmor/src/models/dependabot.rs, crates/zizmor/src/registry.rs, crates/zizmor/tests/integration/snapshot.rs, crates/zizmor/tests/integration/snapshots/integration__snapshot__dependabot_execution.snap, crates/zizmor/tests/integration/test-data/dependabot-execution/basic/dependabot.yml, docs/audits.md, docs/usage.md
This is an initial Dependabot-specific audit, to feel out where the pain points are.
=> feat: dependabot-execution audit
